# Copyright (c) 2026 Peter Hanily
# SPDX-License-Identifier: MIT
"""In-band synthetic marking for parser-classified structured formats.

A bundle can be renamed, a README can be lost, a file can be copied out of its directory by
someone who does not know where it came from. The only disclosure that survives all of that
is one carried inside the bytes, so every format listed in Gate 3's marker table contains an
`ARTIFACTFORGE` anchor that `strings` will find and that a person reading a hex dump cannot
miss. Plain sidecars are outside that table; the serialized quarantine xattr value is the
notable current exception.

This is not decoration and it is not optional. Gate 3 fails any format that ships without
one, checked on the emitted bytes rather than on a promise in a document — which matters,
because KNOWN_TELLS.md claimed exactly this mechanism while nothing enforced it, and four
of six formats carried nothing at all.

Where a format has somewhere natural to put it, it goes there: a reserved table in a SQLite
database, a reserved key in a plist, the overlay of a PE, `__cstring` in a Mach-O. Each is a
place a real artifact's tooling ignores and a responder's `strings` does not.
"""

#: The anchor. Present verbatim, as ASCII, in every parser-classified structured format.
MARKER = "ARTIFACTFORGE"

#: The one-line disclosure that travels with it wherever there is room for prose.
#:
#: Deliberately plain ASCII. A binary plist silently re-encodes any string containing a
#: non-ASCII character as UTF-16, which would hide the anchor from `strings` and from Gate 3
#: — the marker has to survive every container it is put in, not most of them.
NOTICE = ("SYNTHETIC - generated by ArtifactForge for training and evaluation. "
          "This is not evidence and must never be presented as genuine. "
          "Do not submit these hashes or indicators to any blocklist or "
          "threat-intelligence platform.")

#: The name of the reserved SQLite table and the reserved plist key.
RESERVED_NAME = "artifactforge_synthetic"
