# Copyright (c) 2026 Peter Hanily
# SPDX-License-Identifier: MIT
"""Keyed suite derivation — how a deterministic generator can still have unguessable answers.

Determinism and unguessability look like opposites. A batch must regenerate byte-identical
forever, which means every answer is a pure function of something; and the generator is open
source, which means anyone can compute that function. The previous design resolved this by
accident and badly: `scenario_id` was both the label handed to the solver *and* the seed the
answers were derived from, so a solver that opened no file at all scored 100%.

The resolution is a secret, introduced in exactly one place. Every derivation hangs off a
32-byte **suite key**. The public identifier is an HMAC of the key and the index, so it is
stable, deterministic and reproducible *given the key* — and reveals nothing without it.
Domain-separated leaf keys keep the public identifier, the content seed, and each variable
selection independent, so recovering one tells you nothing about the others.

Three kinds of suite, and the difference is the whole point of publishing one:

  **dev** — built with `PUBLIC_DEV_KEY`, which is printed below on purpose. Anyone can
  regenerate it, inspect it, and cheat on it. That is what makes it useful for development
  and useless as a score. `bench grade` refuses to report a bare accuracy for a dev suite.

  **hold-out** — built with a freshly minted random key that never leaves the evaluator.
  Scores are only meaningful here. Generate on one machine, ship `scenarios/` and
  `public.json` to the machine under test, grade back on the first.

  **scorecard-measurement** — built with a separately domain-separated public key. It exists
  only so the committed project scorecard can be regenerated byte-for-byte. Like a dev suite,
  it is deliberately reproducible and therefore never reportable as a benchmark score.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
from pathlib import Path
import secrets

from artifactforge.inventory import (
    InventoryError,
    canonical_relative_paths,
    directory_entry_matches_descriptor,
    inventory_regular_files,
    open_real_directory,
    open_real_directory_at,
    remove_pinned_directory_at,
    rename_directory_no_replace,
    write_regular_file_at,
)

#: Domain separator. Changing it invalidates every derived value, which is the point of
#: versioning it: a v2 suite can never collide with a v1 suite.
DOMAIN = b"artifactforge/bench/v1"

#: Published deliberately. A dev suite is meant to be reproducible and cheatable; the honest
#: move is to say so loudly rather than to pretend a well-known constant is a secret.
PUBLIC_DEV_KEY = b"artifactforge-public-dev-suite-v1"

#: A disclosed seed and a distinct derivation domain for the scorecard measurement corpus.
#: Neither is secret: reproducibility is the purpose, and the resulting suite is explicitly
#: non-reportable. Keeping this separate from PUBLIC_DEV_KEY also stops scorecard measurements
#: from silently becoming the adversary control corpus.
SCORECARD_MEASUREMENT_SEED = b"artifactforge-public-scorecard-measurement-seed-v1"
SCORECARD_MEASUREMENT_KEY_DOMAIN = b"artifactforge/scorecard/measurement-key/v1"
SCORECARD_MEASUREMENT_KIND = "scorecard-measurement"
NON_REPORTABLE_SUITE_KINDS = frozenset(("dev", SCORECARD_MEASUREMENT_KIND))

# Fixture manifests publish their seed and every payload digest. They are reproducibility
# records and therefore answer disclosures inside a benchmark's served tree. Keep this
# boundary in the staging primitive so a future scene builder cannot opt out by accident.
BENCHMARK_FORBIDDEN_FILENAMES = frozenset(("fixture.json",))
_FIXTURE_MANIFEST_MARKER = b"artifactforge-fixture-manifest-v1"

_SEP = b"\x1f"


def _private_stage_directory(parent_fd: int, parent: Path, final_name: str) -> Path:
    """Create an unpublished same-filesystem directory without touching global temp policy."""
    for _attempt in range(32):
        candidate_name = f".{final_name}.stage-{secrets.token_hex(8)}"
        try:
            os.mkdir(candidate_name, mode=0o700, dir_fd=parent_fd)
            return parent / candidate_name
        except FileExistsError:
            continue
        except (NotImplementedError, OSError) as exc:
            raise ValueError(
                f"cannot reserve a private staging directory below {parent}: {exc}"
            ) from exc
    raise ValueError(f"cannot reserve a private staging directory below {parent}")


def _directory_path_matches_descriptor(path: Path, descriptor: int) -> bool:
    try:
        path_state = path.lstat()
        opened = os.fstat(descriptor)
    except OSError:
        return False
    return (
        path_state.st_dev,
        path_state.st_ino,
    ) == (opened.st_dev, opened.st_ino)


def _mac(key: bytes, *parts: str) -> bytes:
    """HMAC-SHA256 over domain-separated parts. Unit separators make the parts unambiguous,
    so ("ab", "c") and ("a", "bc") cannot derive the same value."""
    msg = DOMAIN + _SEP + _SEP.join(p.encode() for p in parts)
    return hmac.new(key, msg, hashlib.sha256).digest()


def new_key() -> bytes:
    """A fresh hold-out key. Lose it and the suite can never be regenerated or audited."""
    return secrets.token_bytes(32)


def scorecard_measurement_key() -> bytes:
    """The public deterministic key used only by ``artifactforge scorecard``.

    Domain separation makes accidental reuse of the dev-suite key visible in both code and
    provenance. This key provides reproducibility, not secrecy; a corpus made from it is never
    a hold-out and must never produce a reportable benchmark score.
    """
    return hmac.new(SCORECARD_MEASUREMENT_SEED, SCORECARD_MEASUREMENT_KEY_DOMAIN,
                    hashlib.sha256).digest()


def scorecard_measurement_key_id() -> str:
    """A non-key fingerprint suitable for a public scorecard provenance block."""
    return "sha256:" + hashlib.sha256(scorecard_measurement_key()).hexdigest()


def scorecard_measurement_provenance(n: int) -> dict:
    """Public provenance for a deterministic, explicitly non-reportable measurement run."""
    return {
        "purpose": "reproducible-scorecard-measurement",
        "suite_kind": SCORECARD_MEASUREMENT_KIND,
        "scenario_count": n,
        "deterministic": True,
        "reportable": False,
        "suite_derivation_domain": DOMAIN.decode(),
        "key_derivation": {
            "algorithm": "HMAC-SHA256",
            "domain": SCORECARD_MEASUREMENT_KEY_DOMAIN.decode(),
            "seed_id": "sha256:" + hashlib.sha256(SCORECARD_MEASUREMENT_SEED).hexdigest(),
            "key_id": scorecard_measurement_key_id(),
        },
    }


def public_id(key: bytes, index: int) -> str:
    """The label a solver sees. Carries no information about the scenario it names."""
    raw = _mac(key, "public-id", str(index))[:10]
    return "af1_" + base64.b32encode(raw).decode().rstrip("=").lower()


def scenario_key(key: bytes, pid: str) -> bytes:
    """A per-scenario leaf key. Everything about one scenario derives from this and nothing
    else, so leaking one scenario's answers cannot compromise another's."""
    return _mac(key, "scenario", pid)


def content_seed(skey: bytes, role: str) -> str:
    """The ContentStore seed for one file in one scenario. `role` distinguishes the target
    binary from each decoy, so decoys are as unguessable as the answer."""
    return _mac(skey, "content", role).hex()


def pick(skey: bytes, field: str, pool):
    """Choose from a pool. Keyed per (scenario, field), which also removes the parity
    degeneracy of the previous `pool[i % len(pool)]`: that reached only half of each
    even-length pool and locked host to user, giving three distinct pairs at any batch size."""
    return pool[int.from_bytes(_mac(skey, "pick", field)[:4], "big") % len(pool)]


def pick_many(skey: bytes, field: str, pool, n: int):
    """`n` distinct choices, deterministically ordered by their keyed rank."""
    ranked = sorted(pool, key=lambda v: _mac(skey, f"{field}:rank", str(v)))
    return ranked[:n]


# --- suite layout on disk ----------------------------------------------------------------
#
#   SUITE/
#     public.json          what the solver is given: kind, version, scenario ids, questions
#     scenarios/<pid>/     the ONLY directory a solver may read
#     _key/key.hex         the suite key (0600). Never inside scenarios/.
#     _answers/<pid>.json  answer key + join manifest
#     _content/<sha256>    the ContentStore cache, deliberately outside the served tree
#                          because its filenames ARE sha256 answers
#
# The underscore prefix is a convention for humans. The guarantee is structural: nothing
# under scenarios/ is a parent of anything else, and staging copies files in by allowlist
# rather than filtering them out of a listing. The previous design wrote JOIN_MANIFEST.json
# into the served directory and hid it from `os.listdir`, which is not a boundary.

def suite_paths(root: str) -> dict:
    return {
        "public": os.path.join(root, "public.json"),
        "scenarios": os.path.join(root, "scenarios"),
        "key": os.path.join(root, "_key", "key.hex"),
        "answers": os.path.join(root, "_answers"),
        "content": os.path.join(root, "_content"),
        "staging": os.path.join(root, "_staging"),
    }


def write_key(root: str, key: bytes) -> None:
    p = suite_paths(root)["key"]
    os.makedirs(os.path.dirname(p), mode=0o700, exist_ok=True)
    with open(p, "w") as f:
        f.write(key.hex())
    os.chmod(p, 0o600)


def read_key(root: str) -> bytes:
    with open(suite_paths(root)["key"]) as f:
        return bytes.fromhex(f.read().strip())


def stage(scene_dir: str, staging_dir: str, allowlist) -> list:
    """Copy exactly the named regular files into a new recursive served tree.

    An allowlist rather than a denylist: the final recursive regular-file inventory equals the
    canonical allowlist by construction, so a new artifact cannot leak into the solver's view
    by being forgotten in a filter. This is the structural half of the fix; the keyed
    derivation is the other half.
    """
    try:
        names = canonical_relative_paths(allowlist)
    except InventoryError as exc:
        raise ValueError(f"unsafe scene allowlist: {exc}") from exc
    if not names:
        raise ValueError("scene allowlist must contain at least one artifact")

    scene_path = Path(scene_dir)
    if not scene_path.name or scene_path.name in {".", ".."}:
        raise ValueError("served scene root must have one non-empty final path component")
    forbidden = sorted(
        name for name in names
        if name.rsplit("/", 1)[-1].casefold() in BENCHMARK_FORBIDDEN_FILENAMES
    )
    if forbidden:
        raise ValueError(
            "fixture manifests publish benchmark answers and cannot enter a served scene: "
            + ", ".join(forbidden)
        )
    try:
        source_inventory = inventory_regular_files(staging_dir, capture_bytes=True)
    except InventoryError as exc:
        raise ValueError(f"unsafe staging tree: {exc}") from exc
    sources = {file.relative_path: file for file in source_inventory}
    missing = sorted(set(names) - set(sources))
    if missing:
        raise ValueError("scene allowlist names missing staging files: " + ", ".join(missing))

    prepared = []
    for name in names:
        data = sources[name].data
        if data is None:  # capture_bytes=True is a construction invariant.
            raise AssertionError("staging inventory did not capture file bytes")
        if _FIXTURE_MANIFEST_MARKER in data:
            raise ValueError(
                "fixture manifests publish benchmark answers and cannot enter a served scene: "
                + name
            )
        prepared.append((name, data))

    try:
        parent_fd = open_real_directory(scene_path.parent)
    except InventoryError as exc:
        raise ValueError(f"served scene parent must be an existing real directory: {exc}") from exc
    try:
        os.stat(scene_path.name, dir_fd=parent_fd, follow_symlinks=False)
    except FileNotFoundError:
        pass
    except (NotImplementedError, OSError) as exc:
        os.close(parent_fd)
        raise ValueError(f"cannot inspect served scene root safely: {exc}") from exc
    else:
        os.close(parent_fd)
        raise ValueError(f"refusing pre-existing served scene root: {scene_path}")

    try:
        temporary = _private_stage_directory(parent_fd, scene_path.parent, scene_path.name)
    except Exception:
        os.close(parent_fd)
        raise
    root_fd = -1
    published = False
    successful = False
    try:
        root_fd = open_real_directory_at(parent_fd, temporary.name)
        if os.listdir(root_fd):
            raise ValueError("temporary served scene root is unexpectedly non-empty")
        for name, data in prepared:
            write_regular_file_at(root_fd, name, data)

        try:
            observed = inventory_regular_files(
                temporary, capture_bytes=True, pinned_root_fd=root_fd
            )
        except InventoryError as exc:
            raise ValueError(f"unsafe staged scene: {exc}") from exc
        observed_payload = tuple((file.relative_path, file.data) for file in observed)
        if observed_payload != tuple(prepared):
            raise ValueError(
                "staged scene inventory or bytes do not equal the canonical allowlist"
            )
        if not _directory_path_matches_descriptor(scene_path.parent, parent_fd):
            raise ValueError("served scene parent changed during staging")
        if not directory_entry_matches_descriptor(parent_fd, temporary.name, root_fd):
            raise ValueError("temporary served scene root changed after verification")
        root_state = os.fstat(root_fd)
        expected_source = root_state.st_dev, root_state.st_ino
        try:
            rename_directory_no_replace(
                temporary,
                scene_path,
                parent_fd=parent_fd,
                expected_source=expected_source,
            )
        except FileExistsError as exc:
            raise ValueError(
                f"refusing served scene root that appeared during staging: {scene_path}"
            ) from exc
        published = True
        if not directory_entry_matches_descriptor(parent_fd, scene_path.name, root_fd):
            raise ValueError("published served scene is not the verified directory")

        # The root stays private through publication and the descriptor-bound final byte
        # check. No verification step needs to reopen the public pathname.
        try:
            final_inventory = inventory_regular_files(
                scene_path, capture_bytes=True, pinned_root_fd=root_fd
            )
        except InventoryError as exc:
            raise ValueError(f"unsafe published scene: {exc}") from exc
        final_payload = tuple((file.relative_path, file.data) for file in final_inventory)
        if final_payload != tuple(prepared):
            raise ValueError("published scene bytes changed after verification")
        if (
            not _directory_path_matches_descriptor(scene_path.parent, parent_fd)
            or not directory_entry_matches_descriptor(parent_fd, scene_path.name, root_fd)
        ):
            raise ValueError("published served scene changed during final verification")
        os.fchmod(root_fd, 0o755)
        successful = True
    finally:
        if root_fd >= 0 and not successful:
            entry_name = scene_path.name if published else temporary.name
            remove_pinned_directory_at(parent_fd, entry_name, root_fd)
        if root_fd >= 0:
            os.close(root_fd)
        elif not published:
            try:
                os.rmdir(temporary.name, dir_fd=parent_fd)
            except OSError:
                pass
        os.close(parent_fd)
    return list(names)


def write_answers(root: str, pid: str, answers: dict, join: dict) -> str:
    d = suite_paths(root)["answers"]
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, f"{pid}.json")
    with open(path, "w") as f:
        json.dump({"scenario_id": pid, "answers": answers, "join": join}, f, indent=2)
        f.write("\n")
    return path


def read_answers(root: str, pid: str) -> dict:
    with open(os.path.join(suite_paths(root)["answers"], f"{pid}.json")) as f:
        return json.load(f)
