# Copyright (c) 2026 Peter Hanily
# SPDX-License-Identifier: MIT
"""Keyed suite derivation — how a deterministic generator can still have unguessable answers.

Determinism and unguessability look like opposites. Under one declared protocol implementation
and ABI, a batch must regenerate byte-identically, which means every answer is a pure function
of something; and the generator is open source, which means anyone can compute that function.
Cross-version identity requires an explicit compatibility contract. The previous design
resolved this by accident and badly: `scenario_id` was both the label handed to the solver
*and* the seed the answers were derived from, so a solver that opened no file at all scored
100%.

The resolution is a secret, introduced in exactly one place. Every derivation hangs off a
32-byte **suite key**. The public identifier is an HMAC of the key and the index, so it is
stable, deterministic and reproducible *given the key* — and reveals nothing without it.
Domain-separated leaf keys keep the public identifier, the content seed, and each variable
selection independent, so recovering one tells you nothing about the others.

Benchmark v2 has three historical suite labels.  They remain parseable so old fixtures and
diagnostics do not acquire new semantics by being loaded with newer code, but every v2 suite
is permanently local and non-reportable:

  **dev** — built with `PUBLIC_DEV_KEY`, which is printed below on purpose. Anyone can
  regenerate it, inspect it, and cheat on it. That is what makes it useful for development
  and useless as a score. `bench grade` refuses to report a bare accuracy for a dev suite.

  **hold-out** — the historical label for a caller-keyed local suite.  A secret key is useful
  diagnostic hygiene, but v2 records no evaluator-created freshness ceremony and can never
  support a reportable result.

  **scorecard-measurement** — built with a separately domain-separated public key. It exists
  only so the committed project scorecard can be regenerated byte-for-byte. Like a dev suite,
  it is deliberately reproducible and therefore never reportable as a benchmark score.

Benchmark v3 is deliberately separate.  Its evaluator-ceremony constructor mints key material
internally, binds an exact origin/reportability block into ``suite_id``, and retains a private
ceremony record.  That is local self-attestation only: external isolation, independence and
one-shot evaluation still require evidence outside this process.
"""

from __future__ import annotations

import base64
from contextlib import contextmanager
from datetime import datetime
import hashlib
import hmac
import json
import os
from pathlib import Path
import re
import secrets
import stat
import tempfile
from types import SimpleNamespace
import unicodedata

from artifactforge.inventory import (
    InventoryError,
    MAX_SCENE_FILES,
    MAX_SCENE_TOTAL_BYTES,
    canonical_relative_paths,
    directory_entry_matches_descriptor,
    freeze_directory_tree,
    inventory_regular_files,
    open_real_directory,
    open_real_directory_at,
    remove_pinned_directory_at,
    rename_directory_no_replace,
    write_regular_file_at,
)

#: Frozen Benchmark v2 domain separator.  Existing v2 documents and fixture bytes retain it.
DOMAIN = b"artifactforge/bench/v2"
BENCHMARK_V3_DOMAIN = b"artifactforge/bench/v3"

# Scene-value derivation was historically (and accidentally) coupled to the benchmark
# protocol domain.  Freeze the old byte contract here so a benchmark-protocol migration does
# not perturb independently versioned Fixture Core and Linux-assurance recipes.  Benchmark
# scenario keys are still v2-derived, so v2 benchmark scenes remain disjoint from v1.
SCENE_VALUE_DOMAIN = b"artifactforge/bench/v1"

#: Published deliberately. A dev suite is meant to be reproducible and cheatable; the honest
#: move is to say so loudly rather than to pretend a well-known constant is a secret.
PUBLIC_DEV_KEY_SEED = b"artifactforge-public-dev-suite-v2"
PUBLIC_DEV_KEY = hashlib.sha256(PUBLIC_DEV_KEY_SEED).digest()
DEV_SUITE_KIND = "dev"
HOLDOUT_SUITE_KIND = "holdout"

# These strings are part of the byte-derivation contract for the two corpora used by
# generator assurance.  They are published in the scorecard so a later namespace change
# cannot be mistaken for a like-for-like measurement.
WINDOWS_MACOS_CONTENT_NAMESPACE = "artifactforge::suite"
GENERATOR_ASSURANCE_LINUX_CONTENT_NAMESPACE = "artifactforge::generator-assurance/linux/v1"
WINDOWS_MACOS_FAMILY_SCHEDULE = "zero-based-index-parity-v1"
GENERATOR_ASSURANCE_LINUX_COUNT_CONTRACT = "ceil-half-windows-macos-v1"
GENERATOR_ASSURANCE_LINUX_KIND = "generator-assurance-linux"

#: A disclosed seed and a distinct derivation domain for the scorecard measurement corpus.
#: Neither is secret: reproducibility is the purpose, and the resulting suite is explicitly
#: non-reportable. Keeping this separate from PUBLIC_DEV_KEY also stops scorecard measurements
#: from silently becoming the adversary control corpus.
SCORECARD_MEASUREMENT_SEED = b"artifactforge-public-scorecard-measurement-seed-v1"
SCORECARD_MEASUREMENT_KEY_DOMAIN = b"artifactforge/scorecard/measurement-key/v1"
SCORECARD_MEASUREMENT_KIND = "scorecard-measurement"
NON_REPORTABLE_SUITE_KINDS = frozenset((DEV_SUITE_KIND, SCORECARD_MEASUREMENT_KIND))
ALLOWED_SUITE_KINDS = frozenset((DEV_SUITE_KIND, HOLDOUT_SUITE_KIND, SCORECARD_MEASUREMENT_KIND))

# Gates 1-3 append a deterministic Linux assurance corpus to the existing Windows/macOS
# scenarios.  It has a separate public derivation so generator assurance cannot silently be
# mistaken for, or leak into, Gate 4's benchmark measurement population.
GENERATOR_ASSURANCE_SEED = b"artifactforge-public-generator-assurance-seed-v1"
GENERATOR_ASSURANCE_KEY_DOMAIN = b"artifactforge/generator-assurance/key/v1"
GENERATOR_ASSURANCE_SCENE_DOMAIN = b"artifactforge/generator-assurance/linux-scene/v1"

# Answer keys, join manifests, ground truth, and Fixture Core manifests are disclosures inside
# a benchmark's served tree. Keep this boundary in the staging primitive so every scene
# builder gets the same recursive, case-insensitive protection by construction.
BENCHMARK_FORBIDDEN_FILENAMES = frozenset(
    (
        "artifact_answers.json",
        "ceremony.json",
        "fixture.json",
        "ground_truth.json",
        "join_manifest.json",
        "key.hex",
    )
)
BENCHMARK_FORBIDDEN_PATH_COMPONENTS = frozenset(
    ("_answers", "_ceremony", "_content", "_key", "_staging")
)
_FIXTURE_MANIFEST_MARKER = b"artifactforge-fixture-manifest-v1"

PUBLIC_DOCUMENT_SCHEMA_V2 = "artifactforge-benchmark-public-v2"
PUBLIC_DOCUMENT_SCHEMA_V3 = "artifactforge-benchmark-public-v3"
# Compatibility name: existing callers and the reproducible scorecard describe v2.
PUBLIC_DOCUMENT_SCHEMA = PUBLIC_DOCUMENT_SCHEMA_V2
PUBLIC_EXPORT_SCHEMA = "artifactforge-benchmark-public-export-v1"
PUBLIC_TREE_CANONICALIZATION = "artifactforge-benchmark-scenarios-tree-v1"
BENCHMARK_ORIGIN_SCHEMA = "artifactforge-benchmark-origin-v1"
BENCHMARK_CEREMONY_SCHEMA = "artifactforge-benchmark-ceremony-private-v1"
BENCHMARK_CEREMONY_MAX_BYTES = 16 * 1024
BENCHMARK_CEREMONY_ENTROPY_SOURCE = "python-secrets-token-bytes/os-csprng"
BENCHMARK_CEREMONY_MODE = "evaluator-ceremony"
BENCHMARK_LEGACY_LOCAL_MODE = "legacy-v2-local"
REPORTABILITY_PERMANENTLY_INELIGIBLE = "permanently-ineligible"
REPORTABILITY_PENDING_EXTERNAL_ATTESTATION = "eligible-pending-external-attestation"
BENCHMARK_CEREMONY_TRUST = (
    "LOCAL SELF-ATTESTATION ONLY: this records local ArtifactForge construction; it does not "
    "attest evaluator independence, solver isolation, key non-disclosure, one-shot grading, "
    "or an external witness."
)
BENCHMARK_CEREMONY_KEY_COMMITMENT_DOMAIN = b"artifactforge/bench/v3/key-commitment/v1\x00"
BENCHMARK_MAX_SCENARIOS = 200
BENCHMARK_V3_MIN_SCENES_PER_FAMILY = 60
BENCHMARK_V3_MIN_SCENARIOS = 2 * BENCHMARK_V3_MIN_SCENES_PER_FAMILY
BENCHMARK_V3_POPULATION_POWER_METHOD = "balanced-zero-based-parity-sparse-power-v1"
BENCHMARK_ARTIFACT_FILES_PER_SCENE = (("windows", 14), ("macos", 16))
BENCHMARK_PUBLIC_JSON_MAX_BYTES = 16 * 1024 * 1024
BENCHMARK_ANSWER_FILE_MAX_BYTES = 1024 * 1024
BENCHMARK_KEY_HEX_BYTES = 64
BENCHMARK_ANSWER_MAX_CHARS = 4096
PUBLIC_EXPORT_LIMITATION = (
    "This filesystem export removes co-located evaluator-private material; arbitrary "
    "same-process filesystem access still requires an OS sandbox or separate trust domain."
)
_PUBLIC_EXPORT_FIELD = "public_export"
_SCENARIO_ID = re.compile(r"af1_[a-z2-7]{16}")
_CEREMONY_ID = re.compile(r"afc1_[a-z2-7]{26}")
_CEREMONY_CREATED_AT = re.compile(
    r"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6}Z"
)

# Scorecard measurement contracts.  These are intentionally public and explicit: changing
# any value makes scorecards incomparable rather than silently moving the benchmark beneath
# a stable-looking number.
WINDOWS_AMCACHE_RULE = "amcache-fileid-byte-agreement-v1"
MACOS_QUARANTINE_RULE = "quarantine-uuid-event-agreement-v1"
BENCHMARK_QUESTION_RULES = (
    ("windows", WINDOWS_AMCACHE_RULE),
    ("macos", MACOS_QUARANTINE_RULE),
)
BENCHMARK_QUESTIONS_PER_SCENE = 5
BENCHMARK_CANDIDATES_PER_QUESTION = 5


def validate_benchmark_scenario_count(value: object) -> int:
    """Return one bounded suite population before generation can touch the filesystem."""
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError("benchmark suite size must be an integer")
    if value < 1 or value > BENCHMARK_MAX_SCENARIOS:
        raise ValueError(f"benchmark suite size must be between 1 and {BENCHMARK_MAX_SCENARIOS}")
    return value


def validate_benchmark_v3_scenario_count(value: object) -> int:
    """Require the balanced population covered by v3's predeclared sparse-power contract."""
    count = validate_benchmark_scenario_count(value)
    if count < BENCHMARK_V3_MIN_SCENARIOS or count % 2:
        raise ValueError(
            "benchmark v3 ceremony size must be an even integer between "
            f"{BENCHMARK_V3_MIN_SCENARIOS} and {BENCHMARK_MAX_SCENARIOS}"
        )
    return count


def benchmark_public_file_count(scenario_count: object) -> int:
    """Exact current public-export file count under the alternating family schedule."""
    count = validate_benchmark_scenario_count(scenario_count)
    per_family = dict(BENCHMARK_ARTIFACT_FILES_PER_SCENE)
    windows = (count + 1) // 2
    macos = count // 2
    return 1 + windows * per_family["windows"] + macos * per_family["macos"]


def benchmark_question_prompt(rule: str, selector: dict) -> str:
    """Return the one canonical public prompt for a closed benchmark rule.

    Prompts are executable protocol, not editorial prose: changing one can create a new
    shortcut or make two otherwise identical suites incomparable.  Keeping their rendering
    beside the public-schema constants lets generation and loading enforce the same bytes.
    """
    if rule == WINDOWS_AMCACHE_RULE:
        if set(selector) != {"lower_case_long_path"}:
            raise ValueError("Windows benchmark selector has a non-canonical shape")
        path = selector["lower_case_long_path"]
        return (
            "In Amcache InventoryApplicationFile, select the row whose "
            f"LowerCaseLongPath is {path!r}. Its FileId records a SHA1. Hash the "
            "resident PE candidates and give the SHA256 of the one whose bytes agree."
        )
    if rule == MACOS_QUARANTINE_RULE:
        if set(selector) != {"xattr_relative_path"}:
            raise ValueError("macOS benchmark selector has a non-canonical shape")
        path = selector["xattr_relative_path"]
        return (
            f"Read the serialized com.apple.quarantine xattr at {path!r}. Join its "
            "event UUID to QuarantineEventsV2 and give that event's data URL."
        )
    raise ValueError(f"unsupported benchmark question rule: {rule!r}")


BENCHMARK_RANDOMIZATION_METHOD = "exact-conditional-scene-permutation-v1"
BENCHMARK_MULTIPLE_TESTING_METHOD = "bonferroni-v1"
BENCHMARK_FAMILYWISE_ALPHA = "1/20"
BENCHMARK_MIN_SCENES_PER_CLASS = 20
BENCHMARK_SIGNAL_PROBABILITY = "1/2"
BENCHMARK_TARGET_POWER = "99/100"
BENCHMARK_COUNTERFACTUAL_ENGINE = "parser-valid-local-effect-v1"
BENCHMARK_COUNTERFACTUAL_CHECKS = {"windows": 20, "macos": 25}
BENCHMARK_MAPPING_WORLD_CONTRACT = {
    "representative_mechanisms": 3,
    "mapping_worlds": 360,
    "parser_valid_artifact_rebuilds": 840,
    "independently_resolved_question_checks": 1800,
    "registered_attack_invariance_checks": 3960,
    "positive_control_answer_checks": 1800,
    "non_identity_control_change_checks": 357,
}
BENCHMARK_REGISTERED_ADVERSARIES = (
    "alternate_link",
    "constant",
    "footprint",
    "lexical",
    "listing",
    "mechanical",
    "metadata",
    "null",
    "pool",
    "scalar",
    "selector",
)
BENCHMARK_COMPLETE_ADVERSARIES = (
    "alternate_link",
    "footprint",
    "lexical",
    "mechanical",
    "metadata",
    "pool",
    "scalar",
    "selector",
)
BENCHMARK_POSITIVE_CONTROL_CHECKS = len(BENCHMARK_COMPLETE_ADVERSARIES) + 2
BENCHMARK_POSITIVE_CONTROL_ORACLE = "independent-observable-ranking-oracle-v2"
BENCHMARK_RANK_UNION_CONTROL = "production-wrapper-independent-dev-measurement-v2"
BENCHMARK_PARTIAL_UNION_CONTROL = "production-partial-wrapper-independent-dev-measurement-v1"
BENCHMARK_ENSEMBLES = ("trained-partial-union-v1", "trained-rank-union-v1")
BENCHMARK_RANDOMIZATION_COMPARISONS = (
    len(BENCHMARK_REGISTERED_ADVERSARIES) + len(BENCHMARK_ENSEMBLES)
) * (len(BENCHMARK_QUESTION_RULES) + 1)
BENCHMARK_V3_SPARSE_CRITICAL_HITS = 86
BENCHMARK_V3_SPARSE_NULL_UPPER_TAIL = (
    "5222497923455294692403294447290741517801278724968303535953508081620860210783057303815035313084947464575063754319831030019/"
    "5634751435316678538981231379598050055113916380030678187489466777600000000000000000000000000000000000000000000000000000000000"
)
BENCHMARK_V3_SPARSE_ALTERNATIVES = (
    {
        "first_scenes_meeting_target": 31,
        "model": "one-fixed-edge-plus-uniform-remaining-bijection-v1",
        "name": "one-correct-edge-every-scene-v1",
        "power_at_60_scenes": (
            "766247553761435222187661962449138880246525069434501807/"
            "766247770432944429179173513575154591809369561091801088"
        ),
        "signal_probability": "1/1",
    },
    {
        "first_scenes_meeting_target": 58,
        "model": "whole-mapping-recovery-mixture-v1",
        "name": "whole-mapping-quarter-scenes-v1",
        "power_at_60_scenes": (
            "175114652661261142599637625675437841746535020944591236572523463965152244346581573534082874586087378762710772314408458732853948794819/"
            "176684706477838432958329750074291851582748389687561895812160620129261977600000000000000000000000000000000000000000000000000000000000"
        ),
        "signal_probability": "1/4",
    },
)

_SEP = b"\x1f"


class _PublicJSONError(ValueError):
    pass


def _public_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise _PublicJSONError(f"duplicate object member: {key!r}")
        result[key] = value
    return result


def _validate_public_json(value: object, where: str = "$") -> None:
    if value is None or isinstance(value, bool):
        return
    if isinstance(value, str):
        if unicodedata.normalize("NFC", value) != value:
            raise _PublicJSONError(f"{where} is not Unicode NFC")
        value.encode("utf-8", errors="strict")
        return
    if isinstance(value, int):
        return
    if isinstance(value, list):
        for index, item in enumerate(value):
            _validate_public_json(item, f"{where}[{index}]")
        return
    if isinstance(value, dict):
        for key, item in value.items():
            if not isinstance(key, str):
                raise _PublicJSONError(f"{where} has a non-string member name")
            _validate_public_json(key, f"{where} member name")
            _validate_public_json(item, f"{where}.{key}")
        return
    raise _PublicJSONError(f"{where} has unsupported JSON type {type(value).__name__}")


def _load_public_json(data: bytes) -> object:
    if data.startswith(b"\xef\xbb\xbf"):
        raise _PublicJSONError("UTF-8 BOM is forbidden")
    try:
        text = data.decode("utf-8", errors="strict")
        value = json.loads(
            text,
            object_pairs_hook=_public_object,
            parse_float=lambda token: (_ for _ in ()).throw(
                _PublicJSONError(f"floating-point JSON number is forbidden: {token}")
            ),
            parse_constant=lambda token: (_ for _ in ()).throw(
                _PublicJSONError(f"non-finite JSON number is forbidden: {token}")
            ),
        )
    except _PublicJSONError:
        raise
    except (UnicodeError, json.JSONDecodeError, RecursionError, ValueError) as exc:
        raise _PublicJSONError(f"invalid JSON: {exc}") from exc
    try:
        _validate_public_json(value)
    except _PublicJSONError:
        raise
    except (UnicodeError, RecursionError) as exc:
        raise _PublicJSONError(f"invalid JSON value: {exc}") from exc
    return value


def _canonical_public_json(value: object) -> bytes:
    _validate_public_json(value)
    try:
        rendered = json.dumps(
            value,
            allow_nan=False,
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        )
    except (TypeError, ValueError, RecursionError) as exc:
        raise _PublicJSONError(f"cannot encode canonical public JSON: {exc}") from exc
    return (rendered + "\n").encode("utf-8", errors="strict")


def _load_canonical_public_json(data: bytes) -> object:
    value = _load_public_json(data)
    if data != _canonical_public_json(value):
        raise _PublicJSONError("public.json is not canonical sorted compact UTF-8 JSON")
    return value


def _private_stage_directory(parent_fd: int, parent: Path, final_name: str) -> Path:
    """Create an unpublished same-filesystem directory without touching global temp policy."""
    for _attempt in range(32):
        candidate_name = f".{final_name}.stage-{secrets.token_hex(8)}"
        try:
            os.mkdir(candidate_name, mode=0o700, dir_fd=parent_fd)
            os.chmod(
                candidate_name,
                0o700,
                dir_fd=parent_fd,
                follow_symlinks=False,
            )
            return parent / candidate_name
        except FileExistsError:
            continue
        except (NotImplementedError, OSError) as exc:
            raise ValueError(
                f"cannot reserve a private staging directory below {parent}: {exc}"
            ) from exc
    raise ValueError(f"cannot reserve a private staging directory below {parent}")


def _directory_path_matches_descriptor(path: Path, descriptor: int) -> bool:
    try:
        path_state = path.lstat()
        opened = os.fstat(descriptor)
    except OSError:
        return False
    return (
        path_state.st_dev,
        path_state.st_ino,
    ) == (opened.st_dev, opened.st_ino)


def _domain_mac(key: bytes, domain: bytes, *parts: str) -> bytes:
    """HMAC-SHA256 over domain-separated parts. Unit separators make the parts unambiguous,
    so ("ab", "c") and ("a", "bc") cannot derive the same value."""
    msg = domain + _SEP + _SEP.join(p.encode() for p in parts)
    return hmac.new(key, msg, hashlib.sha256).digest()


def _mac(key: bytes, *parts: str) -> bytes:
    """Derive benchmark-protocol identities in the current benchmark domain."""
    return _domain_mac(key, DOMAIN, *parts)


def scene_value(skey: bytes, *parts: str) -> bytes:
    """Derive scene-local values under the independently frozen scene byte contract."""
    return _domain_mac(skey, SCENE_VALUE_DOMAIN, *parts)


def new_key() -> bytes:
    """Mint a raw local v2 diagnostic key; this is not a v3 freshness ceremony."""
    return secrets.token_bytes(32)


def scorecard_measurement_key() -> bytes:
    """The public deterministic key used only by ``artifactforge scorecard``.

    Domain separation makes accidental reuse of the dev-suite key visible in both code and
    provenance. This key provides reproducibility, not secrecy; a corpus made from it is never
    a hold-out and must never produce a reportable benchmark score.
    """
    return hmac.new(
        SCORECARD_MEASUREMENT_SEED, SCORECARD_MEASUREMENT_KEY_DOMAIN, hashlib.sha256
    ).digest()


def scorecard_measurement_key_id() -> str:
    """A non-key fingerprint suitable for a public scorecard provenance block."""
    return "sha256:" + hashlib.sha256(scorecard_measurement_key()).hexdigest()


def validate_suite_key_kind(key: bytes, kind: str) -> None:
    """Fail closed unless a suite label agrees with the key's disclosure status."""
    if not isinstance(key, bytes) or len(key) != 32:
        raise ValueError("suite key must be exactly 32 bytes")
    if kind not in ALLOWED_SUITE_KINDS:
        raise ValueError(f"suite kind must be one of {sorted(ALLOWED_SUITE_KINDS)!r}, not {kind!r}")
    scorecard_key = scorecard_measurement_key()
    if kind == DEV_SUITE_KIND and key != PUBLIC_DEV_KEY:
        raise ValueError("dev suite kind requires the published PUBLIC_DEV_KEY")
    if kind == SCORECARD_MEASUREMENT_KIND and key != scorecard_key:
        raise ValueError("scorecard-measurement suite kind requires its published measurement key")
    if kind == HOLDOUT_SUITE_KIND and key in {PUBLIC_DEV_KEY, scorecard_key}:
        raise ValueError("holdout suite kind cannot use a published reproducible key")


def benchmark_v3_protocol_identity() -> dict:
    """Return the exact protocol identity carried by v3 ceremony records."""
    return {
        "domain": BENCHMARK_V3_DOMAIN.decode(),
        "key_derivation": "HMAC-SHA256",
        "public_document_schema": PUBLIC_DOCUMENT_SCHEMA_V3,
        "population_power_contract": {
            "adjusted_per_comparison_alpha": "1/780",
            "alternatives": [dict(value) for value in BENCHMARK_V3_SPARSE_ALTERNATIVES],
            "candidate_count": BENCHMARK_CANDIDATES_PER_QUESTION,
            "comparisons": BENCHMARK_RANDOMIZATION_COMPARISONS,
            "critical_hits_at_60_scenes": BENCHMARK_V3_SPARSE_CRITICAL_HITS,
            "family_schedule": WINDOWS_MACOS_FAMILY_SCHEDULE,
            "familywise_alpha": BENCHMARK_FAMILYWISE_ALPHA,
            "method": BENCHMARK_V3_POPULATION_POWER_METHOD,
            "minimum_scenes_per_family": BENCHMARK_V3_MIN_SCENES_PER_FAMILY,
            "minimum_total_scenarios": BENCHMARK_V3_MIN_SCENARIOS,
            "maximum_total_scenarios": BENCHMARK_MAX_SCENARIOS,
            "multiple_testing": BENCHMARK_MULTIPLE_TESTING_METHOD,
            "null_upper_tail_at_60_scenes": BENCHMARK_V3_SPARSE_NULL_UPPER_TAIL,
            "randomization_method": BENCHMARK_RANDOMIZATION_METHOD,
            "requires_even_population": True,
            "target_power": BENCHMARK_TARGET_POWER,
        },
    }


def ceremony_key_commitment(key: bytes) -> str:
    """Commit to evaluator key bytes without making those bytes public."""
    if not isinstance(key, bytes) or len(key) != 32:
        raise ValueError("ceremony key must be exactly 32 bytes")
    digest = hashlib.sha256(BENCHMARK_CEREMONY_KEY_COMMITMENT_DOMAIN + key).hexdigest()
    return "sha256:" + digest


def ceremony_id_from_entropy(entropy: bytes) -> str:
    """Encode one independently minted 128-bit ceremony identifier."""
    if not isinstance(entropy, bytes) or len(entropy) != 16:
        raise ValueError("ceremony identifier entropy must be exactly 16 bytes")
    return "afc1_" + base64.b32encode(entropy).decode("ascii").rstrip("=").lower()


def _validate_ceremony_created_at(value: object) -> str:
    if not isinstance(value, str) or _CEREMONY_CREATED_AT.fullmatch(value) is None:
        raise ValueError("ceremony created_at must be canonical UTC with six fractional digits")
    try:
        parsed = datetime.strptime(value, "%Y-%m-%dT%H:%M:%S.%fZ")
    except ValueError as exc:
        raise ValueError("ceremony created_at is not a real UTC timestamp") from exc
    if parsed.strftime("%Y-%m-%dT%H:%M:%S.%fZ") != value:
        raise ValueError("ceremony created_at is not canonical")
    return value


def _validate_ceremony_common(document: object, *, schema: str, where: str) -> dict:
    fields = {
        "ceremony_id",
        "created_at",
        "entropy_source",
        "key_commitment",
        "mode",
        "protocol",
        "reportability",
        "schema",
        "trust",
    }
    if not isinstance(document, dict) or set(document) != fields:
        raise ValueError(f"{where} must have the exact ceremony field set")
    if document["schema"] != schema:
        raise ValueError(f"{where} schema must be {schema!r}")
    ceremony_id = document["ceremony_id"]
    if not isinstance(ceremony_id, str) or _CEREMONY_ID.fullmatch(ceremony_id) is None:
        raise ValueError(f"{where} ceremony_id is invalid")
    _validate_ceremony_created_at(document["created_at"])
    if document["entropy_source"] != BENCHMARK_CEREMONY_ENTROPY_SOURCE:
        raise ValueError(f"{where} entropy source identity is missing or changed")
    commitment = document["key_commitment"]
    if not isinstance(commitment, str) or re.fullmatch(r"sha256:[0-9a-f]{64}", commitment) is None:
        raise ValueError(f"{where} key commitment must be a labelled lowercase SHA-256")
    if document["mode"] != BENCHMARK_CEREMONY_MODE:
        raise ValueError(f"{where} origin mode is missing or changed")
    if document["protocol"] != benchmark_v3_protocol_identity():
        raise ValueError(f"{where} protocol identity is missing or changed")
    if document["reportability"] != REPORTABILITY_PENDING_EXTERNAL_ATTESTATION:
        raise ValueError(f"{where} reportability classification is missing or changed")
    if document["trust"] != BENCHMARK_CEREMONY_TRUST:
        raise ValueError(f"{where} local self-attestation limitation is missing or changed")
    return document


def validate_benchmark_origin(origin: object) -> dict:
    """Validate the exact public v3 origin/reportability block."""
    return _validate_ceremony_common(
        origin,
        schema=BENCHMARK_ORIGIN_SCHEMA,
        where="benchmark public origin",
    )


def _build_evaluator_ceremony_documents(
    key: bytes,
    *,
    ceremony_id: str,
    created_at: str,
) -> tuple[dict, dict]:
    """Build paired public/private ceremony documents for the internal v3 constructor."""
    common = {
        "ceremony_id": ceremony_id,
        "created_at": created_at,
        "entropy_source": BENCHMARK_CEREMONY_ENTROPY_SOURCE,
        "key_commitment": ceremony_key_commitment(key),
        "mode": BENCHMARK_CEREMONY_MODE,
        "protocol": benchmark_v3_protocol_identity(),
        "reportability": REPORTABILITY_PENDING_EXTERNAL_ATTESTATION,
        "trust": BENCHMARK_CEREMONY_TRUST,
    }
    origin = {**common, "schema": BENCHMARK_ORIGIN_SCHEMA}
    record = {**common, "schema": BENCHMARK_CEREMONY_SCHEMA}
    validate_benchmark_origin(origin)
    _validate_ceremony_common(
        record,
        schema=BENCHMARK_CEREMONY_SCHEMA,
        where="private ceremony record",
    )
    return origin, record


def benchmark_reportability(document: dict) -> str:
    """Return a protocol-bound classification; v2 can never be promoted by relabelling."""
    if not isinstance(document, dict):
        raise ValueError("benchmark document must be a JSON object")
    schema = document.get("schema")
    if schema in (None, PUBLIC_DOCUMENT_SCHEMA_V2):
        return REPORTABILITY_PERMANENTLY_INELIGIBLE
    if schema == PUBLIC_DOCUMENT_SCHEMA_V3:
        return validate_benchmark_origin(document.get("origin"))["reportability"]
    raise ValueError(f"unknown benchmark public schema: {schema!r}")


def public_dev_key_id() -> str:
    """A non-key fingerprint of the deliberately published development-suite key."""
    return "sha256:" + hashlib.sha256(PUBLIC_DEV_KEY).hexdigest()


def generator_assurance_key() -> bytes:
    """Public deterministic key for non-benchmark Linux assurance scenes."""
    return hmac.new(
        GENERATOR_ASSURANCE_SEED,
        GENERATOR_ASSURANCE_KEY_DOMAIN,
        hashlib.sha256,
    ).digest()


def generator_assurance_key_id() -> str:
    return "sha256:" + hashlib.sha256(generator_assurance_key()).hexdigest()


def linux_assurance_count(windows_macos_scenarios: int) -> int:
    """Append enough Linux scenes to keep three-family assurance balanced within one."""
    windows_macos_scenarios = validate_benchmark_scenario_count(windows_macos_scenarios)
    return (windows_macos_scenarios + 1) // 2


def generator_assurance_provenance(windows_macos_scenarios: int) -> dict:
    linux_scenarios = linux_assurance_count(windows_macos_scenarios)
    windows_macos_family_counts = {
        "windows": (windows_macos_scenarios + 1) // 2,
        "macos": windows_macos_scenarios // 2,
    }
    linux_key_derivation = {
        "algorithm": "HMAC-SHA256",
        "domain": GENERATOR_ASSURANCE_KEY_DOMAIN.decode(),
        "seed_id": "sha256:" + hashlib.sha256(GENERATOR_ASSURANCE_SEED).hexdigest(),
        "key_id": generator_assurance_key_id(),
    }
    return {
        "purpose": "deterministic-generator-assurance",
        "families": ["windows", "macos", "linux"],
        "family_counts": {
            **windows_macos_family_counts,
            "linux": linux_scenarios,
        },
        "windows_macos_scenario_count": windows_macos_scenarios,
        "linux_scenario_count": linux_scenarios,
        "scenario_count": windows_macos_scenarios + linux_scenarios,
        "deterministic": True,
        "benchmark_reportable": False,
        "linux_benchmark_included": False,
        "corpora": {
            "windows_macos": {
                "purpose": "windows-macos-generator-assurance",
                "suite_kind": DEV_SUITE_KIND,
                "families": ["windows", "macos"],
                "scenario_count": windows_macos_scenarios,
                "maximum_scenario_count": BENCHMARK_MAX_SCENARIOS,
                "family_counts": windows_macos_family_counts,
                "deterministic": True,
                "benchmark_reportable": False,
                "suite_derivation_domain": DOMAIN.decode(),
                "scene_value_derivation_domain": SCENE_VALUE_DOMAIN.decode(),
                "public_key": {
                    "source": "PUBLIC_DEV_KEY",
                    "identity_algorithm": "SHA256",
                    "key_id": public_dev_key_id(),
                },
                "content_namespace": WINDOWS_MACOS_CONTENT_NAMESPACE,
                "family_schedule": {
                    "algorithm": WINDOWS_MACOS_FAMILY_SCHEDULE,
                    "index_origin": 0,
                    "even_index_family": "windows",
                    "odd_index_family": "macos",
                },
            },
            "linux": {
                "purpose": "linux-generator-assurance",
                "corpus_kind": GENERATOR_ASSURANCE_LINUX_KIND,
                "family": "linux",
                "scenario_count": linux_scenarios,
                "deterministic": True,
                "benchmark_reportable": False,
                "benchmark_included": False,
                "profile": "linux-glibc-x86_64-loose-v1",
                "scene_derivation_domain": GENERATOR_ASSURANCE_SCENE_DOMAIN.decode(),
                "content_namespace": GENERATOR_ASSURANCE_LINUX_CONTENT_NAMESPACE,
                "count_contract": {
                    "algorithm": GENERATOR_ASSURANCE_LINUX_COUNT_CONTRACT,
                    "windows_macos_scenario_count": windows_macos_scenarios,
                },
                "key_derivation": dict(linux_key_derivation),
            },
        },
    }


def scorecard_measurement_provenance(n: int) -> dict:
    """Public provenance for a deterministic, explicitly non-reportable measurement run."""
    n = validate_benchmark_scenario_count(n)
    return {
        "purpose": "reproducible-scorecard-measurement",
        "scope": "benchmark-validity",
        "suite_kind": SCORECARD_MEASUREMENT_KIND,
        "scenario_count": n,
        "deterministic": True,
        "reportable": False,
        "suite_derivation_domain": DOMAIN.decode(),
        "benchmark_contract": {
            "protocol": {
                "public_document_schema": PUBLIC_DOCUMENT_SCHEMA,
                "public_export_schema": PUBLIC_EXPORT_SCHEMA,
                "tree_canonicalization": PUBLIC_TREE_CANONICALIZATION,
                "suite_derivation_domain": DOMAIN.decode(),
                "scene_value_derivation_domain": SCENE_VALUE_DOMAIN.decode(),
                "public_export_inventory": ["public.json", "scenarios/**"],
                "public_export_limitation": PUBLIC_EXPORT_LIMITATION,
                "same_process_python_is_security_boundary": False,
                "resource_limits": {
                    "maximum_scenarios": BENCHMARK_MAX_SCENARIOS,
                    "current_artifact_files_per_scene": dict(BENCHMARK_ARTIFACT_FILES_PER_SCENE),
                    "public_files_at_maximum": benchmark_public_file_count(BENCHMARK_MAX_SCENARIOS),
                    "recursive_file_limit": MAX_SCENE_FILES,
                    "recursive_total_bytes_limit": MAX_SCENE_TOTAL_BYTES,
                    "public_json_bytes": BENCHMARK_PUBLIC_JSON_MAX_BYTES,
                    "answer_document_bytes": BENCHMARK_ANSWER_FILE_MAX_BYTES,
                    "answer_value_characters": BENCHMARK_ANSWER_MAX_CHARS,
                    "key_hex_bytes": BENCHMARK_KEY_HEX_BYTES,
                },
            },
            "questions": {
                "rules": [
                    {"family": family, "rule": rule} for family, rule in BENCHMARK_QUESTION_RULES
                ],
                "questions_per_scene": BENCHMARK_QUESTIONS_PER_SCENE,
                "candidates_per_question": BENCHMARK_CANDIDATES_PER_QUESTION,
                "answer_assignment": "five-way-bijection-v1",
            },
            "inference": {
                "method": BENCHMARK_RANDOMIZATION_METHOD,
                "ensembles": list(BENCHMARK_ENSEMBLES),
                "randomization_unit": "scene",
                "permutations_per_scene": 120,
                "multiple_testing": BENCHMARK_MULTIPLE_TESTING_METHOD,
                "comparisons": BENCHMARK_RANDOMIZATION_COMPARISONS,
                "familywise_alpha": BENCHMARK_FAMILYWISE_ALPHA,
                "minimum_scenes_per_class": BENCHMARK_MIN_SCENES_PER_CLASS,
                "alternative": {
                    "model": "whole-scene-recovery-mixture-v1",
                    "signal_probability": BENCHMARK_SIGNAL_PROBABILITY,
                },
                "target_power": BENCHMARK_TARGET_POWER,
            },
            "counterfactuals": {
                "engine": BENCHMARK_COUNTERFACTUAL_ENGINE,
                "source_tree_must_remain_unchanged": True,
                "checks_per_scene": dict(BENCHMARK_COUNTERFACTUAL_CHECKS),
                "representative_mapping_world_contract": dict(BENCHMARK_MAPPING_WORLD_CONTRACT),
                "windows_mutations": [
                    "windows-fileid-swap",
                    "windows-fileid-absent",
                    "windows-resident-pe-replacement",
                ],
                "macos_mutations": [
                    "macos-xattr-uuid-swap",
                    "macos-database-uuid-swap",
                    "macos-xattr-uuid-absent",
                ],
            },
            "shortcut_controls": {
                "registered_adversaries": list(BENCHMARK_REGISTERED_ADVERSARIES),
                "complete_adversaries": list(BENCHMARK_COMPLETE_ADVERSARIES),
                "mandatory_positive_controls": BENCHMARK_POSITIVE_CONTROL_CHECKS,
                "union_control": BENCHMARK_PARTIAL_UNION_CONTROL,
                "truth_construction": BENCHMARK_POSITIVE_CONTROL_ORACLE,
                "partial_union_model_control": BENCHMARK_PARTIAL_UNION_CONTROL,
                "rank_union_model_control": BENCHMARK_RANK_UNION_CONTROL,
                "blind_public_key_control": True,
                "parent_escape_control": "co-located-100-exported-0-v1",
            },
        },
        "key_derivation": {
            "algorithm": "HMAC-SHA256",
            "domain": SCORECARD_MEASUREMENT_KEY_DOMAIN.decode(),
            "seed_id": "sha256:" + hashlib.sha256(SCORECARD_MEASUREMENT_SEED).hexdigest(),
            "key_id": scorecard_measurement_key_id(),
        },
        "generator_assurance": generator_assurance_provenance(n),
    }


def public_id(key: bytes, index: int, *, domain: bytes = DOMAIN) -> str:
    """The label a solver sees. Carries no information about the scenario it names."""
    if domain not in {DOMAIN, BENCHMARK_V3_DOMAIN}:
        raise ValueError("unsupported benchmark protocol domain")
    raw = _domain_mac(key, domain, "public-id", str(index))[:10]
    return "af1_" + base64.b32encode(raw).decode().rstrip("=").lower()


def scenario_key(key: bytes, pid: str, *, domain: bytes = DOMAIN) -> bytes:
    """A per-scenario leaf key. Everything about one scenario derives from this and nothing
    else, so leaking one scenario's answers cannot compromise another's."""
    if domain not in {DOMAIN, BENCHMARK_V3_DOMAIN}:
        raise ValueError("unsupported benchmark protocol domain")
    return _domain_mac(key, domain, "scenario", pid)


def content_seed(skey: bytes, role: str) -> str:
    """The ContentStore seed for one file in one scenario. `role` distinguishes the target
    binary from each decoy, so decoys are as unguessable as the answer."""
    return scene_value(skey, "content", role).hex()


def pick(skey: bytes, field: str, pool):
    """Choose from a pool. Keyed per (scenario, field), which also removes the parity
    degeneracy of the previous `pool[i % len(pool)]`: that reached only half of each
    even-length pool and locked host to user, giving three distinct pairs at any batch size."""
    return pool[int.from_bytes(scene_value(skey, "pick", field)[:4], "big") % len(pool)]


def pick_many(skey: bytes, field: str, pool, n: int):
    """`n` distinct choices, deterministically ordered by their keyed rank."""
    ranked = sorted(pool, key=lambda v: scene_value(skey, f"{field}:rank", str(v)))
    return ranked[:n]


# --- suite layout on disk ----------------------------------------------------------------
#
#   SUITE/
#     public.json          what the solver is given: kind, version, scenario ids, questions
#     scenarios/<pid>/     the ONLY directory a solver may read
#     _key/key.hex         the suite key (0600). Never inside scenarios/.
#     _ceremony/ceremony.json
#                          v3-only private local self-attestation (0600)
#     _answers/<pid>.json  artifact-derived evaluator answer key
#     _content/<sha256>    the ContentStore cache, deliberately outside the served tree
#                          because its filenames ARE sha256 answers
#
# The underscore prefix is only a convention for evaluator-side organization. A co-located
# solver can traverse to these siblings, so it is deliberately retained as a Gate 4 positive
# control and is never the public security boundary. ``export_public`` atomically constructs
# the solver view in a distinct root containing exactly canonical ``public.json`` and the
# recursively committed ``scenarios/`` tree. Arbitrary same-process filesystem access still
# requires an OS sandbox, separate account/container, or separate machine.


def suite_paths(root: str) -> dict:
    return {
        "public": os.path.join(root, "public.json"),
        "scenarios": os.path.join(root, "scenarios"),
        "key": os.path.join(root, "_key", "key.hex"),
        "ceremony": os.path.join(root, "_ceremony"),
        "ceremony_record": os.path.join(root, "_ceremony", "ceremony.json"),
        "answers": os.path.join(root, "_answers"),
        "content": os.path.join(root, "_content"),
        "staging": os.path.join(root, "_staging"),
    }


def _read_regular_at(
    parent_fd: int,
    name: str,
    where: str,
    *,
    max_bytes: int | None = None,
) -> bytes:
    """Read one stable, no-follow regular entry below a pinned directory."""
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = -1
    try:
        before = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
        if stat.S_ISLNK(before.st_mode) or not stat.S_ISREG(before.st_mode):
            raise ValueError(f"{where} must be a regular file, not a link or special file")
        descriptor = os.open(name, flags, dir_fd=parent_fd)
        opened = os.fstat(descriptor)
        if not stat.S_ISREG(opened.st_mode) or (opened.st_dev, opened.st_ino) != (
            before.st_dev,
            before.st_ino,
        ):
            raise ValueError(f"{where} changed while it was being opened")
        if max_bytes is not None and opened.st_size > max_bytes:
            raise ValueError(f"{where} exceeds the {max_bytes}-byte input limit")
        chunks = []
        total = 0
        while chunk := os.read(descriptor, 1024 * 1024):
            total += len(chunk)
            if max_bytes is not None and total > max_bytes:
                raise ValueError(f"{where} exceeds the {max_bytes}-byte input limit")
            chunks.append(chunk)
        after_read = os.fstat(descriptor)
        after_path = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
    except ValueError:
        raise
    except (NotImplementedError, OSError) as exc:
        raise ValueError(f"cannot safely read {where}: {exc}") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)
    stable = ("st_dev", "st_ino", "st_size", "st_mtime_ns", "st_ctime_ns")
    if any(
        getattr(opened, field) != getattr(after_read, field)
        or getattr(after_read, field) != getattr(after_path, field)
        for field in stable
    ):
        raise ValueError(f"{where} changed while it was being read")
    data = b"".join(chunks)
    if len(data) != after_read.st_size:
        raise ValueError(f"{where} length changed while it was being read")
    return data


def _require_private_mode(state: os.stat_result, expected: int, where: str) -> None:
    if os.name != "nt" and stat.S_IMODE(state.st_mode) != expected:
        raise ValueError(f"{where} mode must be exactly {expected:#o}")


def _capture_evaluator_state(
    root: str,
) -> tuple[
    bytes,
    tuple[tuple[str, bytes], ...],
    bytes,
    tuple[tuple[str, bytes], ...],
    bytes | None,
]:
    """Capture public, scenario, key, answer and optional ceremony bytes in one pinned view."""
    root_path = Path(root)
    root_fd = scenarios_fd = answers_fd = key_fd = ceremony_fd = -1
    ceremony_bytes = None
    ceremony_names: list[str] | None = None
    ceremony_state: os.stat_result | None = None
    try:
        root_fd = open_real_directory(root_path)
        names = sorted(os.listdir(root_fd))
        public_bytes = _read_regular_at(
            root_fd,
            "public.json",
            "evaluator public.json",
            max_bytes=BENCHMARK_PUBLIC_JSON_MAX_BYTES,
        )
        scenarios_fd = open_real_directory_at(root_fd, "scenarios")
        answers_fd = open_real_directory_at(root_fd, "_answers")
        key_fd = open_real_directory_at(root_fd, "_key")
        key_names = sorted(os.listdir(key_fd))
        if key_names != ["key.hex"]:
            raise ValueError(
                "evaluator key directory must contain exactly the regular file key.hex"
            )
        key_bytes = _read_regular_at(
            key_fd,
            "key.hex",
            "evaluator key",
            max_bytes=BENCHMARK_KEY_HEX_BYTES,
        )
        if "_ceremony" in names:
            ceremony_fd = open_real_directory_at(root_fd, "_ceremony")
            ceremony_names = sorted(os.listdir(ceremony_fd))
            if ceremony_names != ["ceremony.json"]:
                raise ValueError("evaluator ceremony directory must contain exactly ceremony.json")
            ceremony_before = os.stat("ceremony.json", dir_fd=ceremony_fd, follow_symlinks=False)
            ceremony_bytes = _read_regular_at(
                ceremony_fd,
                "ceremony.json",
                "evaluator ceremony record",
                max_bytes=BENCHMARK_CEREMONY_MAX_BYTES,
            )
            ceremony_state = os.stat("ceremony.json", dir_fd=ceremony_fd, follow_symlinks=False)
            stable = ("st_dev", "st_ino", "st_size", "st_mtime_ns", "st_ctime_ns")
            if any(
                getattr(ceremony_before, field) != getattr(ceremony_state, field)
                for field in stable
            ):
                raise ValueError("evaluator ceremony record changed during initial capture")
            _require_private_mode(os.fstat(root_fd), 0o700, "evaluator ceremony root")
            _require_private_mode(os.fstat(ceremony_fd), 0o700, "evaluator ceremony directory")
            _require_private_mode(os.fstat(key_fd), 0o700, "evaluator key directory")
            _require_private_mode(
                os.stat("public.json", dir_fd=root_fd, follow_symlinks=False),
                0o600,
                "evaluator public document",
            )
            _require_private_mode(
                os.stat("key.hex", dir_fd=key_fd, follow_symlinks=False),
                0o600,
                "evaluator key",
            )
            _require_private_mode(
                ceremony_state,
                0o600,
                "evaluator ceremony record",
            )
        try:
            files = inventory_regular_files(
                root_path / "scenarios",
                capture_bytes=True,
                pinned_root_fd=scenarios_fd,
            )
            answer_files = inventory_regular_files(
                root_path / "_answers",
                capture_bytes=True,
                pinned_root_fd=answers_fd,
                max_file_bytes=BENCHMARK_ANSWER_FILE_MAX_BYTES,
            )
        except InventoryError as exc:
            raise ValueError(f"evaluator public or private inventory is unsafe: {exc}") from exc
        captured = []
        for file in files:
            if file.data is None:
                raise AssertionError("public scenario capture contains no bytes")
            captured.append((file.relative_path, file.data))
        captured_answers = []
        for file in answer_files:
            if file.data is None:
                raise AssertionError("private answer capture contains no bytes")
            captured_answers.append((file.relative_path, file.data))
        if not _directory_path_matches_descriptor(root_path, root_fd):
            raise ValueError("evaluator root changed while its public view was captured")
        if not directory_entry_matches_descriptor(root_fd, "scenarios", scenarios_fd):
            raise ValueError("evaluator scenarios root changed while it was captured")
        if not directory_entry_matches_descriptor(root_fd, "_answers", answers_fd):
            raise ValueError("evaluator answers root changed while public data was captured")
        if not directory_entry_matches_descriptor(root_fd, "_key", key_fd):
            raise ValueError("evaluator key root changed while private state was captured")
        if ceremony_fd >= 0 and not directory_entry_matches_descriptor(
            root_fd, "_ceremony", ceremony_fd
        ):
            raise ValueError("evaluator ceremony root changed while private state was captured")
        if sorted(os.listdir(key_fd)) != key_names:
            raise ValueError("evaluator key inventory changed while private state was captured")
        if ceremony_fd >= 0 and sorted(os.listdir(ceremony_fd)) != ceremony_names:
            raise ValueError(
                "evaluator ceremony inventory changed while private state was captured"
            )
        if sorted(os.listdir(root_fd)) != names:
            raise ValueError("evaluator root inventory changed while public data was captured")
        if (
            _read_regular_at(
                root_fd,
                "public.json",
                "evaluator public.json",
                max_bytes=BENCHMARK_PUBLIC_JSON_MAX_BYTES,
            )
            != public_bytes
        ):
            raise ValueError("evaluator public.json changed while public data was captured")
        if (
            _read_regular_at(
                key_fd,
                "key.hex",
                "evaluator key",
                max_bytes=BENCHMARK_KEY_HEX_BYTES,
            )
            != key_bytes
        ):
            raise ValueError("evaluator key changed while private state was captured")
        if ceremony_fd >= 0:
            final_ceremony_bytes = _read_regular_at(
                ceremony_fd,
                "ceremony.json",
                "evaluator ceremony record",
                max_bytes=BENCHMARK_CEREMONY_MAX_BYTES,
            )
            final_ceremony_state = os.stat(
                "ceremony.json", dir_fd=ceremony_fd, follow_symlinks=False
            )
            stable = ("st_dev", "st_ino", "st_size", "st_mtime_ns", "st_ctime_ns")
            if final_ceremony_bytes != ceremony_bytes or any(
                getattr(ceremony_state, field) != getattr(final_ceremony_state, field)
                for field in stable
            ):
                raise ValueError(
                    "evaluator ceremony record changed while private state was captured"
                )
        return (
            public_bytes,
            tuple(captured),
            key_bytes,
            tuple(captured_answers),
            ceremony_bytes,
        )
    except InventoryError as exc:
        raise ValueError(f"evaluator root is unsafe or not private-capable: {exc}") from exc
    finally:
        if ceremony_fd >= 0:
            os.close(ceremony_fd)
        if key_fd >= 0:
            os.close(key_fd)
        if answers_fd >= 0:
            os.close(answers_fd)
        if scenarios_fd >= 0:
            os.close(scenarios_fd)
        if root_fd >= 0:
            os.close(root_fd)


def _capture_scenario_payload(
    scenarios_root: str | os.PathLike[str],
) -> tuple[tuple[str, bytes], ...]:
    """Capture one stable, no-follow scenarios tree for public-document construction."""
    root_path = Path(scenarios_root)
    root_fd = -1
    try:
        root_fd = open_real_directory(root_path)
        try:
            files = inventory_regular_files(
                root_path,
                capture_bytes=True,
                pinned_root_fd=root_fd,
            )
        except InventoryError as exc:
            raise ValueError(f"public scenarios are unsafe: {exc}") from exc
        if not _directory_path_matches_descriptor(root_path, root_fd):
            raise ValueError("public scenarios root changed while it was captured")
        payload = []
        for file in files:
            if file.data is None:
                raise AssertionError("public scenario capture contains no bytes")
            payload.append((file.relative_path, file.data))
        return tuple(payload)
    except InventoryError as exc:
        raise ValueError(f"public scenarios root is unsafe: {exc}") from exc
    finally:
        if root_fd >= 0:
            os.close(root_fd)


def _strict_public_document(data: bytes, where: str) -> dict:
    try:
        value = _load_public_json(data)
    except _PublicJSONError as exc:
        raise ValueError(f"{where} is invalid strict JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"{where} must be a JSON object")
    return value


def _validate_public_inventory(
    public: dict,
    scenario_payload: tuple[tuple[str, bytes], ...],
) -> None:
    """Bind public scenario/artifact declarations to exact captured paths and bytes."""
    is_v3 = "origin" in public
    expected_domain = BENCHMARK_V3_DOMAIN if is_v3 else DOMAIN
    if public.get("domain") != expected_domain.decode():
        raise ValueError(
            f"public suite domain must be {expected_domain.decode()!r} for this protocol"
        )
    if _PUBLIC_EXPORT_FIELD in public:
        raise ValueError("evaluator public.json must not already claim to be a public export")
    if "suite_id" in public or "schema" in public:
        raise ValueError("evaluator public.json contains solver-export identity metadata")
    scenarios = public.get("scenarios")
    if not isinstance(scenarios, list):
        raise ValueError("public suite scenarios must be a JSON list")
    if not scenarios:
        raise ValueError("public suite must contain at least one scenario")
    if len(scenarios) > BENCHMARK_MAX_SCENARIOS:
        raise ValueError(f"public suite exceeds the {BENCHMARK_MAX_SCENARIOS}-scenario limit")
    if is_v3:
        validate_benchmark_v3_scenario_count(len(scenarios))
    suite_kind = public.get("suite_kind")
    if suite_kind not in ALLOWED_SUITE_KINDS:
        raise ValueError(f"public suite suite_kind must be one of {sorted(ALLOWED_SUITE_KINDS)!r}")
    expected_fields = {"domain", "scenarios", "suite_kind"}
    if is_v3:
        expected_fields.add("origin")
    if set(public) != expected_fields:
        raise ValueError("public suite base document does not have the exact protocol field set")
    if is_v3:
        if suite_kind != HOLDOUT_SUITE_KIND:
            raise ValueError("benchmark v3 evaluator ceremonies require suite_kind 'holdout'")
        validate_benchmark_origin(public["origin"])
    expected = []
    seen = set()
    for index, entry in enumerate(scenarios):
        if not isinstance(entry, dict):
            raise ValueError(f"public suite scenario {index} must be a JSON object")
        scenario_id = entry.get("scenario_id")
        if not isinstance(scenario_id, str) or _SCENARIO_ID.fullmatch(scenario_id) is None:
            raise ValueError(
                f"public suite scenario {index} has an invalid scenario_id: {scenario_id!r}"
            )
        if scenario_id in seen:
            raise ValueError(f"public suite has duplicate scenario_id {scenario_id!r}")
        seen.add(scenario_id)
        family = entry.get("family")
        expected_scheduled_family = "windows" if index % 2 == 0 else "macos"
        if family != expected_scheduled_family:
            raise ValueError(
                f"scenario {scenario_id!r} family must be {expected_scheduled_family!r} "
                "under the benchmark zero-based parity schedule"
            )
        questions = entry.get("questions")
        if not isinstance(questions, list):
            raise ValueError(f"scenario {scenario_id!r} questions must be a JSON list")
        if len(questions) != BENCHMARK_QUESTIONS_PER_SCENE:
            raise ValueError(
                f"scenario {scenario_id!r} must contain exactly "
                f"{BENCHMARK_QUESTIONS_PER_SCENE} questions"
            )
        artifacts = entry.get("artifacts")
        if not isinstance(artifacts, list):
            raise ValueError(f"scenario {scenario_id!r} published artifacts must be a JSON list")
        try:
            names = canonical_relative_paths(artifacts, require_sorted=True)
        except InventoryError as exc:
            raise ValueError(
                f"scenario {scenario_id!r} has an invalid published artifact inventory: {exc}"
            ) from exc
        if not names:
            raise ValueError(
                f"scenario {scenario_id!r} published artifact inventory must not be empty"
            )
        forbidden_components = sorted(
            name
            for name in names
            if any(
                component.casefold() in BENCHMARK_FORBIDDEN_PATH_COMPONENTS
                for component in name.split("/")
            )
        )
        if forbidden_components:
            raise ValueError(
                f"scenario {scenario_id!r} published artifact paths use evaluator-private "
                "components: " + ", ".join(forbidden_components)
            )
        if set(entry) != {"artifacts", "family", "questions", "scenario_id"}:
            raise ValueError(f"scenario {scenario_id!r} has fields outside the public task schema")
        seen_questions = set()
        for question_index, question in enumerate(questions):
            if not isinstance(question, dict):
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} must be a JSON object"
                )
            for field in ("id", "prompt", "kind", "rule"):
                if not isinstance(question.get(field), str) or not question[field]:
                    raise ValueError(
                        f"scenario {scenario_id!r} question {question_index} "
                        f"field {field!r} must be a non-empty string"
                    )
            question_id = question["id"]
            expected_question_id = f"{family}_agreement_{question_index + 1:02d}"
            if question_id != expected_question_id:
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} id must be "
                    f"{expected_question_id!r}"
                )
            if question_id in seen_questions:
                raise ValueError(
                    f"scenario {scenario_id!r} has duplicate question id {question_id!r}"
                )
            seen_questions.add(question_id)
            selector = question.get("selector")
            if not isinstance(selector, dict):
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} "
                    "field 'selector' must be a JSON object"
                )
            candidate_count = question.get("candidate_count")
            if (
                candidate_count != BENCHMARK_CANDIDATES_PER_QUESTION
                or type(candidate_count) is not int
            ):
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} "
                    f"field 'candidate_count' must be exactly "
                    f"{BENCHMARK_CANDIDATES_PER_QUESTION}"
                )
            if set(question) != {
                "candidate_count",
                "id",
                "kind",
                "prompt",
                "rule",
                "selector",
            }:
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} "
                    "has fields outside the public question schema"
                )
            rule_contracts = {
                "amcache-fileid-byte-agreement-v1": (
                    "windows",
                    "hash",
                    "lower_case_long_path",
                ),
                "quarantine-uuid-event-agreement-v1": (
                    "macos",
                    "url",
                    "xattr_relative_path",
                ),
            }
            contract = rule_contracts.get(question["rule"])
            if contract is None:
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} "
                    "declares an unsupported public rule"
                )
            expected_family, expected_kind, selector_field = contract
            if family != expected_family or question["kind"] != expected_kind:
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} "
                    "rule/family/kind contract does not agree"
                )
            if (
                set(selector) != {selector_field}
                or not isinstance(selector.get(selector_field), str)
                or not selector[selector_field]
            ):
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} selector "
                    f"must contain only non-empty {selector_field!r}"
                )
            if selector_field == "xattr_relative_path" and selector[selector_field] not in names:
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} xattr selector "
                    "is not an exact declared artifact path"
                )
            if question["prompt"] != benchmark_question_prompt(question["rule"], selector):
                raise ValueError(
                    f"scenario {scenario_id!r} question {question_index} prompt is not "
                    "the canonical closed-rule prompt"
                )
        selectors = [
            (question["rule"], tuple(sorted(question["selector"].items())))
            for question in questions
        ]
        if len(set(selectors)) != BENCHMARK_QUESTIONS_PER_SCENE:
            raise ValueError(f"scenario {scenario_id!r} questions must have five unique selectors")
        expected.extend(f"{scenario_id}/{name}" for name in names)

    observed = [path for path, _data in scenario_payload]
    if set(expected) != set(observed):
        missing = sorted(set(expected) - set(observed))
        extra = sorted(set(observed) - set(expected))
        details = []
        if missing:
            details.append("missing: " + ", ".join(missing))
        if extra:
            details.append("extra: " + ", ".join(extra))
        raise ValueError(
            "public scenario inventory does not equal public.json declarations ("
            + "; ".join(details)
            + ")"
        )
    for relative, data in scenario_payload:
        basename = relative.rsplit("/", 1)[-1].casefold()
        if basename in BENCHMARK_FORBIDDEN_FILENAMES or _FIXTURE_MANIFEST_MARKER in data:
            raise ValueError(
                "evaluator public scenarios contain benchmark-private disclosure material: "
                + relative
            )


def _parse_evaluator_key(data: bytes) -> bytes:
    try:
        text = data.decode("ascii", errors="strict")
        key = bytes.fromhex(text)
    except (UnicodeError, ValueError) as exc:
        raise ValueError("evaluator key must be canonical lowercase hexadecimal") from exc
    if text != key.hex():
        raise ValueError("evaluator key must be canonical lowercase hexadecimal")
    if len(key) != 32:
        raise ValueError("evaluator key must decode to exactly 32 bytes")
    return key


def _validate_evaluator_key_document(key: bytes, document: dict) -> None:
    kind = document.get("suite_kind")
    validate_suite_key_kind(key, kind)
    schema = document.get("schema")
    domain = DOMAIN
    if schema == PUBLIC_DOCUMENT_SCHEMA_V3:
        domain = BENCHMARK_V3_DOMAIN
        origin = validate_benchmark_origin(document.get("origin"))
        if origin["key_commitment"] != ceremony_key_commitment(key):
            raise ValueError("benchmark public origin key commitment does not match evaluator key")
    elif schema != PUBLIC_DOCUMENT_SCHEMA_V2:
        raise ValueError(f"unsupported evaluator benchmark schema: {schema!r}")
    for index, entry in enumerate(document["scenarios"]):
        expected = public_id(key, index, domain=domain)
        if entry["scenario_id"] != expected:
            raise ValueError(f"scenario {index} id is not derived from the evaluator key and index")


def _validate_evaluator_ceremony_record(
    key: bytes,
    document: dict,
    ceremony_bytes: bytes | None,
) -> dict | None:
    schema = document.get("schema")
    if schema == PUBLIC_DOCUMENT_SCHEMA_V2:
        if ceremony_bytes is not None:
            raise ValueError("legacy benchmark v2 evaluator must not contain a ceremony record")
        return None
    if schema != PUBLIC_DOCUMENT_SCHEMA_V3:
        raise ValueError(f"unsupported evaluator benchmark schema: {schema!r}")
    if ceremony_bytes is None:
        raise ValueError("benchmark v3 evaluator is missing its private ceremony record")
    try:
        record = _load_canonical_public_json(ceremony_bytes)
    except _PublicJSONError as exc:
        raise ValueError(f"evaluator ceremony record is not canonical: {exc}") from exc
    record = _validate_ceremony_common(
        record,
        schema=BENCHMARK_CEREMONY_SCHEMA,
        where="private ceremony record",
    )
    expected_origin = {**record, "schema": BENCHMARK_ORIGIN_SCHEMA}
    if document.get("origin") != expected_origin:
        raise ValueError("private ceremony record does not equal the bound public origin")
    if record["key_commitment"] != ceremony_key_commitment(key):
        raise ValueError("private ceremony key commitment does not match evaluator key")
    return record


def _validate_evaluator_disclosures(
    key: bytes,
    public_bytes: bytes,
    document: dict,
    scenario_payload: tuple[tuple[str, bytes], ...],
    answer_payload: tuple[tuple[str, bytes], ...],
) -> None:
    """Reject direct key/private-document disclosure in common serialized forms.

    This is a bounded detector for direct disclosure, not a claim that arbitrary reversible
    or encrypted encodings of the evaluator key can be recognized.
    """
    base32 = base64.b32encode(key)
    key_encodings = {
        key,
        key.hex().encode("ascii"),
        key.hex().upper().encode("ascii"),
        base64.b64encode(key),
        base64.urlsafe_b64encode(key),
        base64.b64encode(key).rstrip(b"="),
        base64.urlsafe_b64encode(key).rstrip(b"="),
        base32,
        base32.rstrip(b"="),
        base32.lower(),
        base32.rstrip(b"=").lower(),
    }
    if any(encoded and encoded in public_bytes for encoded in key_encodings):
        raise ValueError("evaluator key material appears inside public.json")
    answer_documents = {data for _relative, data in answer_payload}
    question_ids = {
        question["id"].encode("utf-8")
        for entry in document["scenarios"]
        for question in entry["questions"]
    }
    for relative, data in scenario_payload:
        if any(encoded and encoded in data for encoded in key_encodings):
            raise ValueError("evaluator key material appears inside a served artifact: " + relative)
        if any(private and private in data for private in answer_documents):
            raise ValueError(
                "evaluator answer document appears inside a served artifact: " + relative
            )
        if any(question_id in data for question_id in question_ids):
            raise ValueError("evaluator question id appears inside a served artifact: " + relative)
        if (b'"answers"' in data and b'"scenario_id"' in data) or b'"benchmark_relations"' in data:
            raise ValueError(
                "evaluator-private JSON shape appears inside a served artifact: " + relative
            )


def _validate_evaluator_answers(
    document: dict,
    answer_payload: tuple[tuple[str, bytes], ...],
) -> dict[str, dict]:
    expected_names = {f"{entry['scenario_id']}.json" for entry in document["scenarios"]}
    observed_names = {relative for relative, _data in answer_payload}
    if observed_names != expected_names:
        missing = sorted(expected_names - observed_names)
        extra = sorted(observed_names - expected_names)
        details = []
        if missing:
            details.append("missing: " + ", ".join(missing))
        if extra:
            details.append("extra: " + ", ".join(extra))
        raise ValueError(
            "evaluator answer inventory does not exactly match public scenarios ("
            + "; ".join(details)
            + ")"
        )

    entries = {entry["scenario_id"]: entry for entry in document["scenarios"]}
    parsed = {}
    for relative, data in answer_payload:
        scenario_id = relative.removesuffix(".json")
        answer_document = _strict_public_document(data, f"evaluator answer {relative!r}")
        if set(answer_document) != {"answers", "scenario_id"}:
            raise ValueError(
                f"evaluator answer {relative!r} must contain exactly answers/scenario_id"
            )
        if answer_document["scenario_id"] != scenario_id:
            raise ValueError(
                f"evaluator answer {relative!r} scenario_id does not match its filename"
            )
        answers = answer_document["answers"]
        if not isinstance(answers, dict):
            raise ValueError(f"evaluator answer {relative!r} answers must be an object")
        expected_question_ids = {question["id"] for question in entries[scenario_id]["questions"]}
        if set(answers) != expected_question_ids:
            raise ValueError(
                f"evaluator answer {relative!r} keys do not exactly match public questions"
            )
        if not all(
            isinstance(value, str) and 0 < len(value) <= BENCHMARK_ANSWER_MAX_CHARS
            for value in answers.values()
        ):
            raise ValueError(
                f"evaluator answer {relative!r} values must be non-empty strings no longer "
                f"than {BENCHMARK_ANSWER_MAX_CHARS} characters"
            )
        parsed[scenario_id] = answer_document
    return parsed


def _validate_evaluator_answer_truth(
    document: dict,
    answers: dict[str, dict],
    scenario_payload: tuple[tuple[str, bytes], ...],
) -> None:
    """Re-derive every answer from the one captured artifact snapshot."""
    from artifactforge.bench.reference_solver import resolve_task

    with tempfile.TemporaryDirectory(prefix="artifactforge-evaluator-snapshot-") as directory:
        os.chmod(directory, 0o700)
        root_fd = open_real_directory(directory)
        try:
            for relative, data in scenario_payload:
                write_regular_file_at(root_fd, relative, data)
            freeze_directory_tree(root_fd)
            for entry in document["scenarios"]:
                questions = [SimpleNamespace(**question) for question in entry["questions"]]
                task = SimpleNamespace(
                    scenario_id=entry["scenario_id"],
                    family=entry["family"],
                    directory=os.fspath(Path(directory) / entry["scenario_id"]),
                    questions=questions,
                    suite_kind=document["suite_kind"],
                    artifacts=tuple(entry["artifacts"]),
                )
                derived = {
                    question_id: resolution.value
                    for question_id, resolution in resolve_task(task).items()
                }
                if answers[entry["scenario_id"]]["answers"] != derived:
                    raise ValueError(
                        f"evaluator answers for {entry['scenario_id']!r} do not equal "
                        "artifact-derived closed-rule truth"
                    )
        finally:
            # TemporaryDirectory cannot remove a read-only tree until modes are restored.
            from artifactforge.inventory import _clear_pinned_directory

            _clear_pinned_directory(root_fd)
            os.close(root_fd)


def _validated_evaluator_state(
    root: str,
    *,
    verify_answers: bool = True,
) -> tuple[dict, bytes, dict[str, dict], tuple[tuple[str, bytes], ...]]:
    public_bytes, scenario_payload, key_bytes, answer_payload, ceremony_bytes = (
        _capture_evaluator_state(root)
    )
    public = _strict_public_document(public_bytes, "evaluator public.json")
    document = _validated_or_built_public_document(public, scenario_payload)
    if "suite_id" in public and public_bytes != _canonical_public_json(public):
        raise ValueError("evaluator public.json protocol document is not canonical")
    key = _parse_evaluator_key(key_bytes)
    _validate_evaluator_key_document(key, document)
    _validate_evaluator_ceremony_record(key, document, ceremony_bytes)
    _validate_evaluator_disclosures(key, public_bytes, document, scenario_payload, answer_payload)
    answers = _validate_evaluator_answers(document, answer_payload)
    if verify_answers:
        _validate_evaluator_answer_truth(document, answers, scenario_payload)
    return document, key, answers, scenario_payload


def load_evaluator_private(root: str) -> tuple[dict, dict[str, dict]]:
    """Load one evaluator suite and its strictly bound private answer documents."""
    document, _key, answers, _scenario_payload = _validated_evaluator_state(root)
    return document, answers


def load_evaluator_public(root: str) -> dict:
    """Validate the solver document in an evaluator root retaining private answers."""
    document, _key, _answers, _scenario_payload = _validated_evaluator_state(root)
    return document


def validate_evaluator_key_binding(root: str, public: dict | None = None) -> bytes:
    """Validate evaluator disclosure status and return the exact bound 32-byte key."""
    document, key, _answers, _scenario_payload = _validated_evaluator_state(
        root, verify_answers=False
    )
    if public is not None and document != public:
        raise ValueError("evaluator public document changed across key-binding validation")
    return key


def _scenario_tree_commitment(
    scenario_payload: tuple[tuple[str, bytes], ...],
) -> dict:
    # Individual artifact digests remain evaluator-private because several are benchmark
    # answers. Only this aggregate tree commitment crosses into the solver document.
    files = [
        {
            "path": f"scenarios/{relative}",
            "sha256": "sha256:" + hashlib.sha256(data).hexdigest(),
            "size": len(data),
        }
        for relative, data in scenario_payload
    ]
    digest_input = {
        "canonicalization": PUBLIC_TREE_CANONICALIZATION,
        "files": files,
    }
    return {
        "canonicalization": PUBLIC_TREE_CANONICALIZATION,
        "file_count": len(files),
        "total_size": sum(item["size"] for item in files),
        "tree_sha256": "sha256:" + hashlib.sha256(_canonical_public_json(digest_input)).hexdigest(),
    }


def _build_public_export_document(
    public: dict,
    scenario_payload: tuple[tuple[str, bytes], ...],
) -> dict:
    schema = PUBLIC_DOCUMENT_SCHEMA_V3 if "origin" in public else PUBLIC_DOCUMENT_SCHEMA_V2
    document = {
        **public,
        "schema": schema,
        _PUBLIC_EXPORT_FIELD: {
            "payload": _scenario_tree_commitment(scenario_payload),
            "schema": PUBLIC_EXPORT_SCHEMA,
            "limitation": PUBLIC_EXPORT_LIMITATION,
        },
    }
    suite_id = "sha256:" + hashlib.sha256(_canonical_public_json(document)).hexdigest()
    return {**document, "suite_id": suite_id}


def build_public_document(
    public: dict,
    scenarios_root: str | os.PathLike[str],
) -> dict:
    """Build a v2 or v3 public document bound to exact aggregate scenarios-tree bytes.

    Per-file digests are deliberately confined to the commitment preimage: publishing them
    would disclose answer-bearing hashes in several benchmark families.
    """
    if not isinstance(public, dict):
        raise ValueError("public suite base document must be a JSON object")
    scenario_payload = _capture_scenario_payload(scenarios_root)
    _validate_public_inventory(public, scenario_payload)
    return _build_public_export_document(public, scenario_payload)


def canonical_public_bytes(document: dict) -> bytes:
    """Encode a public document as the suite's single canonical JSON representation."""
    if not isinstance(document, dict):
        raise ValueError("public suite document must be a JSON object")
    try:
        return _canonical_public_json(document)
    except _PublicJSONError as exc:
        raise ValueError(f"public suite document cannot be canonicalized: {exc}") from exc


def _validate_public_export_document(
    document: dict,
    scenario_payload: tuple[tuple[str, bytes], ...],
) -> None:
    schema = document.get("schema")
    if schema not in {PUBLIC_DOCUMENT_SCHEMA_V2, PUBLIC_DOCUMENT_SCHEMA_V3}:
        raise ValueError(
            "solver public schema must be one of "
            f"{[PUBLIC_DOCUMENT_SCHEMA_V2, PUBLIC_DOCUMENT_SCHEMA_V3]!r}"
        )
    if (schema == PUBLIC_DOCUMENT_SCHEMA_V3) != ("origin" in document):
        raise ValueError("solver public schema and origin block do not identify one protocol")
    suite_id = document.get("suite_id")
    if not isinstance(suite_id, str) or re.fullmatch(r"sha256:[0-9a-f]{64}", suite_id) is None:
        raise ValueError("solver public suite_id must be a labelled lowercase SHA-256")
    export = document.get(_PUBLIC_EXPORT_FIELD)
    if not isinstance(export, dict) or set(export) != {"limitation", "payload", "schema"}:
        raise ValueError("solver public export metadata has an invalid shape")
    if export["schema"] != PUBLIC_EXPORT_SCHEMA:
        raise ValueError(f"solver public export schema must be {PUBLIC_EXPORT_SCHEMA!r}")
    if export["limitation"] != PUBLIC_EXPORT_LIMITATION:
        raise ValueError("solver public export limitation is missing or changed")
    payload = export["payload"]
    if not isinstance(payload, dict) or set(payload) != {
        "canonicalization",
        "file_count",
        "total_size",
        "tree_sha256",
    }:
        raise ValueError("solver public aggregate payload commitment has an invalid shape")

    unsigned = dict(document)
    unsigned.pop("suite_id")
    expected_suite_id = "sha256:" + hashlib.sha256(_canonical_public_json(unsigned)).hexdigest()
    if suite_id != expected_suite_id:
        raise ValueError("solver public suite_id does not bind the canonical public document")

    source_public = dict(unsigned)
    source_public.pop("schema")
    source_public.pop(_PUBLIC_EXPORT_FIELD)
    _validate_public_inventory(source_public, scenario_payload)
    expected_payload = _scenario_tree_commitment(scenario_payload)
    if payload != expected_payload:
        raise ValueError("solver public aggregate payload commitment does not match scenario bytes")


def _validated_or_built_public_document(
    public: dict,
    scenario_payload: tuple[tuple[str, bytes], ...],
) -> dict:
    """Accept exact protocol documents while retaining the v2 bare-document migration path."""
    identity_fields = ("schema", "suite_id", _PUBLIC_EXPORT_FIELD)
    if any(field in public for field in identity_fields):
        _validate_public_export_document(public, scenario_payload)
        return public
    _validate_public_inventory(public, scenario_payload)
    return _build_public_export_document(public, scenario_payload)


def _prepared_public_export(
    document: dict,
    scenario_payload: tuple[tuple[str, bytes], ...],
) -> tuple[tuple[str, bytes], ...]:
    prepared = [("public.json", _canonical_public_json(document))]
    prepared.extend((f"scenarios/{relative}", data) for relative, data in scenario_payload)
    return tuple(sorted(prepared))


def _public_export_summary(document: dict) -> dict:
    return {
        "schema": document["schema"],
        "suite_id": document["suite_id"],
        "payload": document[_PUBLIC_EXPORT_FIELD]["payload"],
        "limitation": PUBLIC_EXPORT_LIMITATION,
    }


def _capture_public_export(
    root: str,
    *,
    pinned_root_fd: int | None = None,
) -> tuple[dict, tuple[tuple[str, bytes], ...]]:
    """Capture and validate one exact solver export without returning live path state.

    When ``pinned_root_fd`` is supplied, the complete byte capture is rooted in that held
    directory inode.  ``root`` remains only its display pathname, so a concurrent rename or
    case-insensitive path alias cannot make validation inspect a different export.
    """
    root_path = Path(root)
    try:
        files = inventory_regular_files(
            root_path,
            capture_bytes=True,
            pinned_root_fd=pinned_root_fd,
        )
    except InventoryError as exc:
        raise ValueError(f"solver input is not a safe exact public export: {exc}") from exc
    by_path = {file.relative_path: file.data for file in files}
    public_bytes = by_path.get("public.json")
    if public_bytes is None:
        raise ValueError("solver input is not a public export: canonical public.json is missing")
    if len(public_bytes) > BENCHMARK_PUBLIC_JSON_MAX_BYTES:
        raise ValueError(
            f"solver public.json exceeds the {BENCHMARK_PUBLIC_JSON_MAX_BYTES}-byte input limit"
        )
    unexpected = sorted(
        path for path in by_path if path != "public.json" and not path.startswith("scenarios/")
    )
    if unexpected:
        # Name the shape of the mistake, not the contents of the evaluator root.  This is the
        # error a solver hits when it is pointed at the private tree, and echoing every path
        # back at them would hand over the private inventory the export exists to withhold.
        raise ValueError(
            f"solver input is not a public export: it holds {len(unexpected)} entries outside "
            "public.json and scenarios/. Point this at the directory produced by "
            "'artifactforge bench export', not at the evaluator root"
        )
    scenario_payload = tuple(
        (path.removeprefix("scenarios/"), data)
        for path, data in sorted(by_path.items())
        if path.startswith("scenarios/") and data is not None
    )
    try:
        document = _load_canonical_public_json(public_bytes)
    except _PublicJSONError as exc:
        raise ValueError(f"solver public.json is not canonical: {exc}") from exc
    if not isinstance(document, dict):
        raise ValueError("solver public.json must be a JSON object")
    _validate_public_export_document(document, scenario_payload)
    expected_paths = {path for path, _data in _prepared_public_export(document, scenario_payload)}
    if set(by_path) != expected_paths:
        missing = sorted(expected_paths - set(by_path))
        extra = sorted(set(by_path) - expected_paths)
        details = []
        if missing:
            details.append("missing: " + ", ".join(missing))
        if extra:
            details.append("extra: " + ", ".join(extra))
        raise ValueError("solver public export inventory is not exact (" + "; ".join(details) + ")")
    return document, scenario_payload


def load_public_export(root: str, *, pinned_root_fd: int | None = None) -> dict:
    """Load a solver-facing root only if its complete recursive bytes match public.json."""
    document, _scenario_payload = _capture_public_export(
        root,
        pinned_root_fd=pinned_root_fd,
    )
    return document


@contextmanager
def frozen_public_export(root: str, *, pinned_root_fd: int | None = None):
    """Yield a private read-only copy of one captured and validated solver export."""
    document, scenario_payload = _capture_public_export(
        root,
        pinned_root_fd=pinned_root_fd,
    )
    prepared = _prepared_public_export(document, scenario_payload)
    directory = Path(tempfile.mkdtemp(prefix="artifactforge-public-snapshot-"))
    root_fd = open_real_directory(directory)
    try:
        for relative, data in prepared:
            write_regular_file_at(root_fd, relative, data)
        observed = inventory_regular_files(directory, capture_bytes=True, pinned_root_fd=root_fd)
        if tuple((file.relative_path, file.data) for file in observed) != prepared:
            raise ValueError("private solver snapshot differs from the captured public export")
        freeze_directory_tree(root_fd)
        yield document, directory
    finally:
        from artifactforge.inventory import _clear_pinned_directory

        _clear_pinned_directory(root_fd)
        os.close(root_fd)
        try:
            directory.rmdir()
        except OSError:
            pass


def _is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def _publish_public_tree(
    output: Path,
    prepared: tuple[tuple[str, bytes], ...],
    *,
    evaluator_root: Path,
) -> None:
    if not output.name or output.name in {".", ".."}:
        raise ValueError("public export must name a new directory below an existing parent")
    try:
        parent = output.parent.resolve(strict=True)
        evaluator = evaluator_root.resolve(strict=True)
    except OSError as exc:
        raise ValueError("evaluator and public-export parent must already exist") from exc
    destination = parent / output.name
    if _is_within(destination, evaluator) or _is_within(evaluator, destination):
        raise ValueError("public export and evaluator root must be disjoint")

    try:
        parent_fd = open_real_directory(parent)
    except InventoryError as exc:
        raise ValueError(f"public export parent must be an existing real directory: {exc}") from exc
    try:
        os.stat(output.name, dir_fd=parent_fd, follow_symlinks=False)
    except FileNotFoundError:
        pass
    except (NotImplementedError, OSError) as exc:
        os.close(parent_fd)
        raise ValueError(f"cannot inspect public export destination safely: {exc}") from exc
    else:
        os.close(parent_fd)
        raise ValueError(f"refusing pre-existing public export destination: {destination}")

    try:
        temporary = _private_stage_directory(parent_fd, parent, output.name)
    except Exception:
        os.close(parent_fd)
        raise
    root_fd = -1
    published = successful = False
    try:
        root_fd = open_real_directory_at(parent_fd, temporary.name)
        for relative, data in prepared:
            write_regular_file_at(root_fd, relative, data)
        try:
            staged = inventory_regular_files(
                temporary,
                capture_bytes=True,
                pinned_root_fd=root_fd,
            )
        except InventoryError as exc:
            raise ValueError(f"staged public export is unsafe: {exc}") from exc
        staged_payload = tuple((file.relative_path, file.data) for file in staged)
        if staged_payload != prepared:
            raise ValueError("staged public export inventory or bytes are not exact")
        if not _directory_path_matches_descriptor(parent, parent_fd):
            raise ValueError("public export parent changed during staging")
        if not directory_entry_matches_descriptor(parent_fd, temporary.name, root_fd):
            raise ValueError("temporary public export changed after verification")
        root_state = os.fstat(root_fd)
        try:
            rename_directory_no_replace(
                temporary,
                destination,
                parent_fd=parent_fd,
                expected_source=(root_state.st_dev, root_state.st_ino),
            )
        except FileExistsError as exc:
            raise ValueError(
                f"refusing public export destination that appeared during staging: {destination}"
            ) from exc
        published = True
        if not directory_entry_matches_descriptor(parent_fd, output.name, root_fd):
            raise ValueError("published public export is not the verified staged directory")
        try:
            final = inventory_regular_files(
                destination,
                capture_bytes=True,
                pinned_root_fd=root_fd,
            )
        except InventoryError as exc:
            raise ValueError(f"published public export is unsafe: {exc}") from exc
        final_payload = tuple((file.relative_path, file.data) for file in final)
        if final_payload != prepared:
            raise ValueError("published public export bytes changed after verification")
        if not _directory_path_matches_descriptor(
            parent, parent_fd
        ) or not directory_entry_matches_descriptor(parent_fd, output.name, root_fd):
            raise ValueError("published public export changed during final verification")
        freeze_directory_tree(root_fd, file_mode=0o444, directory_mode=0o555)
        successful = True
    finally:
        if root_fd >= 0 and not successful:
            entry_name = output.name if published else temporary.name
            remove_pinned_directory_at(parent_fd, entry_name, root_fd)
        if root_fd >= 0:
            os.close(root_fd)
        elif not published:
            try:
                os.rmdir(temporary.name, dir_fd=parent_fd)
            except OSError:
                pass
        os.close(parent_fd)


def export_public(
    evaluator_root: str,
    public_root: str,
    *,
    expected_document: dict | None = None,
) -> dict:
    """Publish an exact no-replace solver root containing only public.json and scenarios/."""
    document, _key, _answers, scenario_payload = _validated_evaluator_state(evaluator_root)
    if expected_document is not None and document != expected_document:
        raise ValueError("evaluator public bytes changed after CLI validation")
    prepared = _prepared_public_export(document, scenario_payload)
    _publish_public_tree(
        Path(public_root),
        prepared,
        evaluator_root=Path(evaluator_root),
    )
    return _public_export_summary(document)


def write_key(root: str, key: bytes) -> None:
    if not isinstance(key, bytes) or len(key) != 32:
        raise ValueError("suite key must be exactly 32 bytes")
    p = suite_paths(root)["key"]
    os.makedirs(os.path.dirname(p), mode=0o700, exist_ok=True)
    os.chmod(os.path.dirname(p), 0o700)
    with open(p, "x") as f:
        f.write(key.hex())
    os.chmod(p, 0o600)


def _write_ceremony_record(root_fd: int, record: dict) -> None:
    """Exclusively create one canonical private ceremony record below an owned root."""
    _validate_ceremony_common(
        record,
        schema=BENCHMARK_CEREMONY_SCHEMA,
        where="private ceremony record",
    )
    try:
        payload = _canonical_public_json(record)
    except _PublicJSONError as exc:
        raise ValueError(f"private ceremony record cannot be canonicalized: {exc}") from exc
    if len(payload) > BENCHMARK_CEREMONY_MAX_BYTES:
        raise ValueError("private ceremony record exceeds its protocol byte limit")
    try:
        write_regular_file_at(root_fd, "_ceremony/ceremony.json", payload, mode=0o600)
    except InventoryError as exc:
        raise ValueError(f"cannot publish private ceremony record safely: {exc}") from exc


def read_key(root: str) -> bytes:
    return validate_evaluator_key_binding(root)


def stage(scene_dir: str, staging_dir: str, allowlist) -> list:
    """Copy exactly the named regular files into a new recursive served tree.

    An allowlist rather than a denylist: the final recursive regular-file inventory equals the
    canonical allowlist by construction, so a new artifact cannot leak into the solver's view
    by being forgotten in a filter. This is the structural half of the fix; the keyed
    derivation is the other half.
    """
    try:
        names = canonical_relative_paths(allowlist)
    except InventoryError as exc:
        raise ValueError(f"unsafe scene allowlist: {exc}") from exc
    if not names:
        raise ValueError("scene allowlist must contain at least one artifact")

    scene_path = Path(scene_dir)
    if not scene_path.name or scene_path.name in {".", ".."}:
        raise ValueError("served scene root must have one non-empty final path component")
    forbidden = sorted(
        name
        for name in names
        if name.rsplit("/", 1)[-1].casefold() in BENCHMARK_FORBIDDEN_FILENAMES
    )
    if forbidden:
        raise ValueError(
            "benchmark disclosure metadata cannot enter a served scene: " + ", ".join(forbidden)
        )
    try:
        source_inventory = inventory_regular_files(staging_dir, capture_bytes=True)
    except InventoryError as exc:
        raise ValueError(f"unsafe staging tree: {exc}") from exc
    sources = {file.relative_path: file for file in source_inventory}
    missing = sorted(set(names) - set(sources))
    if missing:
        raise ValueError("scene allowlist names missing staging files: " + ", ".join(missing))

    prepared = []
    for name in names:
        data = sources[name].data
        if data is None:  # capture_bytes=True is a construction invariant.
            raise AssertionError("staging inventory did not capture file bytes")
        if _FIXTURE_MANIFEST_MARKER in data:
            raise ValueError("benchmark disclosure metadata cannot enter a served scene: " + name)
        prepared.append((name, data))

    try:
        parent_fd = open_real_directory(scene_path.parent)
    except InventoryError as exc:
        raise ValueError(f"served scene parent must be an existing real directory: {exc}") from exc
    try:
        os.stat(scene_path.name, dir_fd=parent_fd, follow_symlinks=False)
    except FileNotFoundError:
        pass
    except (NotImplementedError, OSError) as exc:
        os.close(parent_fd)
        raise ValueError(f"cannot inspect served scene root safely: {exc}") from exc
    else:
        os.close(parent_fd)
        raise ValueError(f"refusing pre-existing served scene root: {scene_path}")

    try:
        temporary = _private_stage_directory(parent_fd, scene_path.parent, scene_path.name)
    except Exception:
        os.close(parent_fd)
        raise
    root_fd = -1
    published = False
    successful = False
    try:
        root_fd = open_real_directory_at(parent_fd, temporary.name)
        if os.listdir(root_fd):
            raise ValueError("temporary served scene root is unexpectedly non-empty")
        for name, data in prepared:
            write_regular_file_at(root_fd, name, data)

        try:
            observed = inventory_regular_files(
                temporary, capture_bytes=True, pinned_root_fd=root_fd
            )
        except InventoryError as exc:
            raise ValueError(f"unsafe staged scene: {exc}") from exc
        observed_payload = tuple((file.relative_path, file.data) for file in observed)
        if observed_payload != tuple(prepared):
            raise ValueError("staged scene inventory or bytes do not equal the canonical allowlist")
        if not _directory_path_matches_descriptor(scene_path.parent, parent_fd):
            raise ValueError("served scene parent changed during staging")
        if not directory_entry_matches_descriptor(parent_fd, temporary.name, root_fd):
            raise ValueError("temporary served scene root changed after verification")
        root_state = os.fstat(root_fd)
        expected_source = root_state.st_dev, root_state.st_ino
        try:
            rename_directory_no_replace(
                temporary,
                scene_path,
                parent_fd=parent_fd,
                expected_source=expected_source,
            )
        except FileExistsError as exc:
            raise ValueError(
                f"refusing served scene root that appeared during staging: {scene_path}"
            ) from exc
        published = True
        if not directory_entry_matches_descriptor(parent_fd, scene_path.name, root_fd):
            raise ValueError("published served scene is not the verified directory")

        # The root stays private through publication and the descriptor-bound final byte
        # check. No verification step needs to reopen the public pathname.
        try:
            final_inventory = inventory_regular_files(
                scene_path, capture_bytes=True, pinned_root_fd=root_fd
            )
        except InventoryError as exc:
            raise ValueError(f"unsafe published scene: {exc}") from exc
        final_payload = tuple((file.relative_path, file.data) for file in final_inventory)
        if final_payload != tuple(prepared):
            raise ValueError("published scene bytes changed after verification")
        if not _directory_path_matches_descriptor(
            scene_path.parent, parent_fd
        ) or not directory_entry_matches_descriptor(parent_fd, scene_path.name, root_fd):
            raise ValueError("published served scene changed during final verification")
        os.fchmod(root_fd, 0o755)
        successful = True
    finally:
        if root_fd >= 0 and not successful:
            entry_name = scene_path.name if published else temporary.name
            remove_pinned_directory_at(parent_fd, entry_name, root_fd)
        if root_fd >= 0:
            os.close(root_fd)
        elif not published:
            try:
                os.rmdir(temporary.name, dir_fd=parent_fd)
            except OSError:
                pass
        os.close(parent_fd)
    return list(names)


def write_answers(root: str, pid: str, answers: dict) -> str:
    d = suite_paths(root)["answers"]
    os.makedirs(d, mode=0o700, exist_ok=True)
    os.chmod(d, 0o700)
    path = os.path.join(d, f"{pid}.json")
    with open(path, "x") as f:
        json.dump({"scenario_id": pid, "answers": answers}, f, indent=2)
        f.write("\n")
    os.chmod(path, 0o600)
    return path


def read_answers(root: str, pid: str) -> dict:
    _document, answers = load_evaluator_private(root)
    try:
        return answers[pid]
    except KeyError as exc:
        raise ValueError(f"scenario {pid!r} has no evaluator answer document") from exc
